def q(question, correct, wrong1, wrong2, wrong3, explanation, difficulty="medium"):
    return {
        "question": question,
        "options": [
            {"text": correct, "is_correct": True},
            {"text": wrong1,  "is_correct": False},
            {"text": wrong2,  "is_correct": False},
            {"text": wrong3,  "is_correct": False},
        ],
        "explanation": explanation,
        "difficulty":  difficulty,
    }

QUESTIONS = {
    # ── Módulo 1 — Ambiente, Salud y Cuerpo ──────────────────────────────────
    1: [
        q(
            "¿Cuál es la definición de salud según la OMS presentada en el módulo?",
            "Estado de completo bienestar físico, mental y social, y no solo la ausencia de enfermedades",
            "Ausencia de enfermedades físicas diagnosticables",
            "Capacidad de trabajar sin limitaciones físicas ni mentales",
            "Equilibrio entre mente y cuerpo logrado mediante tratamiento médico",
            "El módulo establece que la salud es un estado de completo bienestar físico, mental y social, y no solo la ausencia de enfermedades.",
            difficulty="easy",
        ),
        q(
            "¿Qué término médico describe la micción excesiva (orinar en exceso)?",
            "Poliuria",
            "Polidipsia",
            "Hiperglicemia",
            "Acantosis nigricans",
            "El módulo presenta el caso clínico de una niña con diabetes tipo 2 y describe poliuria como orina en exceso, y polidipsia como sed excesiva.",
            difficulty="easy",
        ),
        q(
            "En el caso clínico del módulo, ¿qué hallazgo de laboratorio descartó la diabetes tipo 1?",
            "Autoanticuerpos negativos",
            "Hiperglicemia leve",
            "Hiperinsulinemia moderada",
            "Hemoglobina glicosilada elevada",
            "El módulo indica que los resultados de laboratorio mostraron autoanticuerpos negativos, lo que descarta la diabetes tipo 1 (que es autoinmune) y confirma el diagnóstico de tipo 2.",
            difficulty="medium",
        ),
        q(
            "¿Qué figura histórica dominó la medicina durante siglos tras la caída del Imperio Romano?",
            "Galeno",
            "Hipócrates",
            "Harvey",
            "Vesalio",
            "El módulo señala que Galeno fue una figura prominente del siglo II d.C. cuyos textos dominaron la medicina durante siglos; con la caída de Roma, Europa retornó a explicaciones mágicas.",
            difficulty="medium",
        ),
        q(
            "El tratamiento de la niña del caso clínico combina metformina, dieta y actividad física. ¿Qué concepto del módulo justifica este enfoque integral?",
            "La salud abarca el bienestar físico, mental y social, por lo que requiere intervenciones que atiendan todas esas dimensiones",
            "La diabetes tipo 2 no responde a la dieta sola, por lo que el fármaco es el único tratamiento eficaz",
            "La salud se define como ausencia de enfermedad, y eliminar la hiperglicemia es suficiente",
            "El módulo recomienda el tratamiento farmacológico exclusivo para casos pediátricos",
            "El módulo define la salud como estado de completo bienestar físico, mental y social. El tratamiento integral (fármaco + dieta + ejercicio) refleja esa visión multidimensional y no solo la eliminación del síntoma.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 2 — Ciencias de la Vida ───────────────────────────────────────
    2: [
        q(
            "¿Qué científico definió la ecología como el estudio del ambiente y la interacción entre organismos?",
            "Ernst Haeckel",
            "Charles Darwin",
            "Gregor Mendel",
            "Robert Hooke",
            "El módulo indica que Ernst Haeckel definió la ecología como el estudio del ambiente y la interacción entre organismos.",
            difficulty="easy",
        ),
        q(
            "¿Qué instrumento permitió grandes avances en el estudio de los seres vivos a partir del siglo XVII?",
            "El microscopio",
            "El telescopio",
            "El espectroscopio",
            "El tomógrafo",
            "El módulo señala que el microscopio, inventado en el siglo XVII, permitió grandes avances en el conocimiento de los seres vivos.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia fundamental entre el mecanicismo y el vitalismo según el módulo?",
            "El mecanicismo sostiene que los seres vivos son como máquinas; el vitalismo argumenta que poseen un 'fluido vital' que los distingue de la materia inanimada",
            "El mecanicismo acepta la evolución; el vitalismo la rechaza",
            "El vitalismo usa el método científico; el mecanicismo no",
            "Ambas corrientes coinciden en que la vida puede explicarse solo con física y química",
            "El módulo describe que el mecanicismo (Descartes, Galileo) comparaba a los seres vivos con máquinas, mientras que el vitalismo argumentaba que los seres vivos poseen un 'fluido vital' que los distingue de los objetos inertes.",
            difficulty="medium",
        ),
        q(
            "¿Por qué la biología es fundamental para las ciencias de la salud como Medicina y Enfermería?",
            "Porque permite comprender el funcionamiento del cuerpo humano, el desarrollo de enfermedades y las necesidades nutricionales",
            "Porque enseña a clasificar organismos en reinos y phyla",
            "Porque estudia únicamente la interacción de átomos y moléculas inorgánicas",
            "Porque es la única ciencia que estudia el comportamiento humano",
            "El módulo indica que las ciencias de la salud dependen de los conocimientos biológicos para comprender el funcionamiento del cuerpo, el desarrollo de enfermedades y las necesidades nutricionales.",
            difficulty="medium",
        ),
        q(
            "Según el módulo, ¿por qué sin la biología la vida sería vista solo como una interacción de átomos?",
            "Porque la biología aporta el estudio de los niveles de organización propios de los seres vivos, algo que la física y la química por sí solas no explican",
            "Porque la física y la química son más exactas que la biología y describen mejor la vida",
            "Porque los átomos son la unidad fundamental de todos los seres vivos según la biología moderna",
            "Porque la biología incluye matemáticas en su metodología, lo que la hace más completa",
            "El módulo plantea que sin la biología, la vida sería entendida solo como interacción de átomos a través de la física y la química; la biología agrega el estudio de los niveles de organización que caracterizan a los seres vivos.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 3 — Moléculas Inorgánicas y Orgánicas ─────────────────────────
    3: [
        q(
            "¿Cuáles son los bioelementos primarios que representan el 96,2% de la masa de los seres vivos?",
            "Carbono, oxígeno, hidrógeno, nitrógeno, fósforo y azufre",
            "Sodio, potasio, calcio y cloro",
            "Hierro, yodo, magnesio y fósforo",
            "Carbono, zinc, flúor y cobre",
            "El módulo indica que los bioelementos primarios (C, O, H, N, P, S) representan el 96,2% de la masa de los seres vivos.",
            difficulty="easy",
        ),
        q(
            "¿Cuáles son las cuatro biomoléculas principales de los seres vivos?",
            "Carbohidratos, lípidos, proteínas y ácidos nucleicos",
            "Lípidos, proteínas, vitaminas y minerales",
            "Glucosa, aminoácidos, ácidos grasos y ADN",
            "Carbohidratos, vitaminas, enzimas y agua",
            "El módulo enumera las cuatro biomoléculas principales: carbohidratos, lípidos, proteínas y ácidos nucleicos.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia entre un bioelemento secundario y un oligoelemento?",
            "Los oligoelementos están presentes en menos del 0,1% y son esenciales en ciertas formas de vida; los secundarios están en mayor proporción pero también son imprescindibles",
            "Los oligoelementos forman parte del ADN; los secundarios no",
            "Los secundarios son tóxicos en exceso; los oligoelementos nunca lo son",
            "No existe diferencia; ambos términos son sinónimos en bioquímica",
            "El módulo distingue: los bioelementos secundarios (Na⁺, K⁺, Ca²⁺, Cl⁻) son imprescindibles pero en menor proporción, mientras que los oligoelementos (Fe, I) están por debajo del 0,1%.",
            difficulty="medium",
        ),
        q(
            "Un átomo de sodio (Na) pierde un electrón y se convierte en Na⁺. ¿Cómo clasifica el módulo a esta partícula?",
            "Es un ion; los iones como Na⁺ son bioelementos secundarios imprescindibles para los seres vivos",
            "Es un átomo; los átomos cargados no existen en biología",
            "Es una molécula; forma parte de las sustancias simples",
            "Es una sustancia compuesta; se forma al unirse con otro elemento",
            "El módulo define a los iones como átomos que ganaron o perdieron electrones. Na⁺ es clasificado como bioelemento secundario (ion de sodio), imprescindible para los seres vivos.",
            difficulty="medium",
        ),
        q(
            "¿Por qué el carbono es el elemento clave para la formación de biomoléculas según el módulo?",
            "Porque tiene la capacidad de formar múltiples enlaces covalentes estables, permitiendo cadenas y anillos complejos",
            "Porque es el elemento más abundante en la corteza terrestre y de fácil obtención",
            "Porque sus átomos son los más pequeños entre los bioelementos primarios",
            "Porque reacciona exclusivamente con oxígeno, formando el esqueleto de todas las biomoléculas",
            "El módulo indica que el carbono es clave por su capacidad de formar múltiples enlaces covalentes estables, lo que permite construir las cadenas y anillos que componen a las biomoléculas.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 4 — Célula: la Unidad de los Seres Vivos ──────────────────────
    4: [
        q(
            "¿Cuándo se estima que aparecieron las primeras células en la Tierra?",
            "Hace entre 3.400 y 3.500 millones de años",
            "Hace 100 millones de años",
            "Hace 500 millones de años",
            "Hace 1.000 millones de años",
            "El módulo establece que se estima que las primeras células aparecieron hace entre 3.400 y 3.500 millones de años.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la célula más pequeña conocida mencionada en el módulo?",
            "Mycoplasma genitalium (0,2 µm)",
            "Eritrocito",
            "Neurona",
            "Bacteria Escherichia coli",
            "El módulo señala que la célula más pequeña conocida es Mycoplasma genitalium, con 0,2 µm de tamaño.",
            difficulty="easy",
        ),
        q(
            "¿Cuáles son las tres propiedades emergentes que distinguen a las células de otros sistemas químicos?",
            "Membrana externa, enzimas para reacciones metabólicas y capacidad de reproducción",
            "Capacidad de moverse, crecer y comunicarse con otras células",
            "Núcleo definido, pared celular y mitocondrias",
            "ADN circular, flagelos y capacidad de fotosíntesis",
            "El módulo identifica tres propiedades emergentes: membrana externa que separa el interior del exterior celular, enzimas que participan en reacciones metabólicas esenciales, y capacidad de reproducción.",
            difficulty="medium",
        ),
        q(
            "¿Por qué existe tanta diversidad de formas celulares en el cuerpo humano?",
            "Porque la forma de cada célula está relacionada con la función que desempeña",
            "Porque cada célula tiene un genoma completamente diferente",
            "Porque las células cambian de forma constantemente para adaptarse al entorno",
            "Porque el tamaño celular determina la forma en todos los casos",
            "El módulo indica que la forma de las células está directamente relacionada con su función; por ejemplo, las células alargadas del miocardio permiten la contracción, y los axones neuronales pueden medir hasta un metro.",
            difficulty="medium",
        ),
        q(
            "¿Por qué el módulo afirma que el estudio de las alteraciones celulares explica el paso 'de la salud a la enfermedad'?",
            "Porque la célula es la unidad estructural y funcional de todos los seres vivos, por lo que sus alteraciones afectan directamente las funciones vitales del organismo",
            "Porque las células solo se alteran por factores genéticos, que determinan todas las enfermedades conocidas",
            "Porque los biólogos celulares estudian exclusivamente enfermedades infecciosas",
            "Porque la microscopía permite identificar directamente todos los virus causantes de enfermedades",
            "El módulo establece que la célula es la unidad estructural y funcional de todos los seres vivos y que todas las funciones vitales ocurren en ellas. Por eso, cualquier alteración celular impacta en la salud del organismo.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 5 — Metabolismo ────────────────────────────────────────────────
    5: [
        q(
            "¿Cuál es la principal fuente de energía utilizada en las reacciones metabólicas celulares?",
            "ATP (adenosín trifosfato)",
            "Glucosa",
            "ADP",
            "NADH",
            "El módulo indica que el ATP (adenosín trifosfato) es la principal fuente de energía utilizada en las reacciones metabólicas de las células.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia básica entre anabolismo y catabolismo?",
            "El anabolismo sintetiza moléculas y es endergónico; el catabolismo rompe moléculas y es exergónico",
            "El anabolismo libera energía; el catabolismo la almacena",
            "El anabolismo ocurre solo en plantas; el catabolismo solo en animales",
            "El catabolismo produce ATP directamente; el anabolismo consume ADP",
            "El módulo define el anabolismo como reacciones de síntesis que requieren energía (endergónicas), y el catabolismo como ruptura de moléculas que liberan energía (exergónicas).",
            difficulty="easy",
        ),
        q(
            "¿Qué función cumplen las enzimas en el metabolismo celular?",
            "Actúan como catalizadores biológicos de naturaleza proteica que aceleran las reacciones químicas",
            "Proporcionan la energía necesaria para las reacciones metabólicas",
            "Almacenan el ATP para ser usado cuando la célula lo necesita",
            "Transportan oxígeno a las mitocondrias durante la respiración celular",
            "El módulo define a las enzimas como catalizadores biológicos de naturaleza proteica que aceleran las reacciones metabólicas.",
            difficulty="medium",
        ),
        q(
            "¿Por qué en individuos jóvenes predomina el anabolismo y en etapas seniles el catabolismo?",
            "Porque en la juventud el organismo está en fase de crecimiento y construcción, mientras que en la vejez predominan los procesos de degradación",
            "Porque los jóvenes consumen más calorías y los adultos mayores menos",
            "Porque las enzimas de catabolismo aparecen solo con la edad y desplazan a las anabólicas",
            "Porque la fotosíntesis es la única fuente de anabolismo y disminuye con la edad",
            "El módulo establece que en individuos jóvenes el anabolismo predomina (fase de crecimiento), mientras que en etapas seniles el catabolismo se vuelve predominante.",
            difficulty="medium",
        ),
        q(
            "Además del envejecimiento, ¿en qué otra condición puede alterarse el equilibrio dinámico entre anabolismo y catabolismo según el módulo?",
            "En condiciones patológicas",
            "Solo en condiciones de alta ingesta calórica sostenida",
            "Únicamente durante el sueño profundo",
            "Solo cuando el organismo está en ayuno prolongado superior a 72 horas",
            "El módulo indica que el equilibrio dinámico entre anabolismo y catabolismo varía a lo largo de la vida y también puede alterarse en condiciones patológicas.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 6 — Mecanismos de Transporte ──────────────────────────────────
    6: [
        q(
            "¿Qué tipo de transporte NO requiere energía y ocurre a favor del gradiente de concentración?",
            "Transporte pasivo",
            "Transporte activo",
            "Endocitosis",
            "Exocitosis",
            "El módulo define el transporte pasivo como el desplazamiento de moléculas a favor de su gradiente de concentración sin requerir energía.",
            difficulty="easy",
        ),
        q(
            "¿Qué moléculas pueden difundir directamente a través de la bicapa lipídica sin necesidad de proteínas?",
            "O₂ y CO₂",
            "Glucosa y aminoácidos",
            "Iones de sodio y potasio",
            "Proteínas y polisacáridos",
            "El módulo indica que las moléculas no polares pequeñas como O₂ y CO₂ se disuelven fácilmente en la bicapa lipídica y difunden rápidamente sin necesidad de proteínas.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia entre proteínas de canal y proteínas transportadoras (carriers)?",
            "Las proteínas de canal crean poros hidrófilos para difusión de iones; las carriers modifican su conformación para transportar moléculas una a la vez",
            "Las proteínas de canal transportan moléculas orgánicas; las carriers solo iones inorgánicos",
            "Las carriers no requieren gradiente de concentración; las de canal sí",
            "Ambas funcionan de la misma manera pero en distintas membranas celulares",
            "El módulo distingue: las proteínas de canal crean poros hidrófilos para difusión (principalmente iones), mientras que las carriers modifican su conformación y transportan una molécula a la vez, como un molinete.",
            difficulty="medium",
        ),
        q(
            "¿Por qué los iones y moléculas cargadas no pueden cruzar directamente la bicapa lipídica?",
            "Porque la bicapa lipídica es impermeable a partículas con carga eléctrica",
            "Porque son demasiado grandes para atravesar cualquier membrana biológica",
            "Porque requieren ATP para activarse antes de atravesar la membrana",
            "Porque solo pueden moverse en contra de su gradiente de concentración",
            "El módulo indica que los iones y moléculas cargadas no pueden atravesar la bicapa lipídica ya que esta es impermeable a ellos, independientemente de su tamaño.",
            difficulty="medium",
        ),
        q(
            "¿Qué factores determinan el movimiento neto de moléculas a través de la membrana según el módulo?",
            "Los gradientes de concentración, presión o carga eléctrica, que proporcionan la energía potencial para el desplazamiento",
            "Únicamente la temperatura y la presión atmosférica del entorno celular",
            "Solo la presencia de proteínas transportadoras en la membrana plasmática",
            "La temperatura celular y el tipo de lípidos presentes en la bicapa",
            "El módulo explica que el movimiento neto de moléculas se guía por gradientes de concentración, presión o carga eléctrica, que proporcionan la energía potencial necesaria.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 7 — Síntesis de Proteínas ─────────────────────────────────────
    7: [
        q(
            "¿Cuáles son los tres tipos funcionales de ARN según el módulo?",
            "ARN mensajero (ARNm), ARN de transferencia (ARNt) y ARN ribosomal (ARNr)",
            "ARN mensajero, ARN de transporte y ARN nuclear",
            "ARN codificante, ARN no codificante y ARN mitocondrial",
            "ARN mensajero, ARN polimerasa y ARN ribosomal",
            "El módulo identifica tres tipos de ARN: ARNm (transporta información genética al citoplasma), ARNt (traduce información en aminoácidos) y ARNr (participa en la síntesis proteica en ribosomas).",
            difficulty="easy",
        ),
        q(
            "¿Cuántos codones posibles existen en el código genético?",
            "64",
            "20",
            "4",
            "128",
            "El módulo indica que existen 64 combinaciones de codones posibles (palabras de tres bases), suficientes para codificar los 20 aminoácidos.",
            difficulty="easy",
        ),
        q(
            "¿Por qué el código genético se dice que es 'redundante'?",
            "Porque un aminoácido puede ser codificado por varios codones distintos",
            "Porque varios aminoácidos pueden ser codificados por el mismo codón",
            "Porque cada codón puede codificar para más de un aminoácido diferente",
            "Porque existen más aminoácidos que codones en el código genético",
            "El módulo explica que el código genético es redundante porque un aminoácido puede ser codificado por varios codones, aunque cada codón solo codifica un aminoácido.",
            difficulty="medium",
        ),
        q(
            "¿En qué organelo ocurre la síntesis de proteínas?",
            "En los ribosomas del citoplasma",
            "En el núcleo celular",
            "En las mitocondrias",
            "En el aparato de Golgi",
            "El módulo indica que en las células eucariotas la síntesis de proteínas ocurre en los ribosomas del citoplasma, aunque el ADN se encuentra en el núcleo.",
            difficulty="medium",
        ),
        q(
            "¿Por qué es necesario el ARN como molécula intermediaria entre el ADN y la síntesis proteica en células eucariotas?",
            "Porque el ADN está confinado en el núcleo y los ribosomas están en el citoplasma; el ARNm lleva la información genética del ADN a los ribosomas",
            "Porque el ADN es inestable fuera del núcleo y se degrada antes de llegar al citoplasma",
            "Porque las proteínas no pueden sintetizarse directamente a partir de bases nitrogenadas",
            "Porque el ARN tiene mayor cantidad de información genética que el ADN",
            "El módulo explica que en eucariotas el ADN está en el núcleo y los ribosomas en el citoplasma; el ARNm actúa como intermediario transportando la información genética del ADN al lugar de síntesis proteica.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 8 — Reproducción Celular ──────────────────────────────────────
    8: [
        q(
            "¿Cuáles son las tres etapas de la interfase del ciclo celular?",
            "G1, S y G2",
            "Profase, metafase y anafase",
            "G0, G1 y S",
            "Interfase temprana, media y tardía",
            "El módulo indica que la interfase se subdivide en G1 (crecimiento citoplasmático), S (replicación del ADN) y G2 (preparación para la división).",
            difficulty="easy",
        ),
        q(
            "¿Qué proceso distribuye equitativamente el citoplasma y los orgánulos entre las dos células hijas?",
            "La citocinesis",
            "La mitosis",
            "La meiosis",
            "La interfase",
            "El módulo indica que la citocinesis distribuye equitativamente el citoplasma y los orgánulos entre las dos células hijas, luego de la separación de los cromosomas.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia principal entre la reproducción de células procariotas y eucariotas?",
            "Las procariotas tienen ADN circular y se dividen más simplemente en dos células hijas idénticas; las eucariotas realizan un proceso más complejo mediante mitosis",
            "Las procariotas se reproducen por meiosis; las eucariotas por mitosis",
            "Las eucariotas no pueden reproducirse asexualmente",
            "Las procariotas requieren dos células para reproducirse; las eucariotas solo una",
            "El módulo indica que las procariotas tienen una sola molécula de ADN circular y se dividen directamente en dos células hijas idénticas; las eucariotas realizan la mitosis con distribución de cromosomas, un proceso más complejo.",
            difficulty="medium",
        ),
        q(
            "¿Qué ocurre específicamente en la fase S del ciclo celular?",
            "El ADN se replica",
            "La célula crece y aumenta sus estructuras citoplasmáticas",
            "La célula se prepara metabólicamente para la división",
            "Los cromosomas se condensan y se separan hacia los polos",
            "El módulo define la fase S como la etapa en que el ADN se replica, duplicando el material genético en preparación para la división celular.",
            difficulty="medium",
        ),
        q(
            "¿Por qué la reproducción asistida y la fecundación natural comparten el mismo objetivo biológico pero usan mecanismos distintos?",
            "Porque ambas buscan unir espermatozoide y óvulo para formar un cigoto, pero la reproducción asistida interviene médicamente cuando existen dificultades para el proceso natural",
            "Porque la reproducción asistida genera células genéticamente distintas a las de la fecundación natural",
            "Porque la inseminación artificial reemplaza al espermatozoide con material genético sintético",
            "Porque en la reproducción asistida ocurre clonación celular en lugar de fecundación",
            "El módulo explica que la reproducción asistida facilita el mismo proceso biológico (unión de espermatozoide y óvulo) mediante técnicas médicas como la inseminación artificial, útil cuando los espermatozoides tienen dificultades para alcanzar el útero.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 9 — Genética ───────────────────────────────────────────────────
    9: [
        q(
            "¿Con qué planta realizó Mendel sus experimentos históricos sobre la herencia?",
            "Guisante (Pisum sativum)",
            "Maíz",
            "Rosa",
            "Arabidopsis thaliana",
            "El módulo indica que Mendel estudió principalmente la reproducción de plantas de guisantes (Pisum sativum), que crecen rápido y completan una generación en una temporada.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia entre fenotipo y genotipo?",
            "El fenotipo es la apariencia externa del organismo; el genotipo es su constitución genética",
            "El fenotipo es la constitución genética; el genotipo es la apariencia externa",
            "Fenotipo y genotipo son sinónimos en genética moderna",
            "El fenotipo incluye solo los caracteres recesivos; el genotipo solo los dominantes",
            "El módulo distingue: el fenotipo es la apariencia externa del organismo, mientras que el genotipo es su constitución genética (la combinación de alelos que posee).",
            difficulty="easy",
        ),
        q(
            "¿Qué establece la Primera Ley de Mendel (Ley de la Uniformidad)?",
            "Si se cruzan dos razas puras, los descendientes de la F1 serán iguales entre sí y a uno de los progenitores",
            "Los alelos de un gen segregan de manera independiente a los de otro gen",
            "Cada individuo posee un par de factores para cada característica y estos se separan al formar los gametos",
            "Las características recesivas nunca se expresan en la primera generación filial",
            "La Primera Ley o Ley de la Uniformidad establece que al cruzar dos razas puras (homocigotas), los descendientes de F1 son iguales entre sí y a uno de los progenitores (el dominante).",
            difficulty="medium",
        ),
        q(
            "¿Cuándo se expresa un alelo recesivo en un organismo?",
            "Cuando ambos alelos del par son recesivos (homocigosis recesiva)",
            "Cuando está presente en cualquier combinación, incluso con un alelo dominante",
            "Solo en la primera generación filial (F1)",
            "Siempre que el organismo sea heterocigoto (Aa)",
            "El módulo indica que los alelos recesivos solo se expresan en homocigosis (cuando ambos alelos son recesivos, ej. aa); en heterocigosis, el dominante enmascara al recesivo.",
            difficulty="medium",
        ),
        q(
            "La Tercera Ley de Mendel demostró que en la F2 aparecen combinaciones de características no presentes en generaciones anteriores. ¿Qué implicación tiene esto para la variabilidad genética?",
            "Que los alelos de distintos genes segregan de manera independiente, generando nuevas combinaciones fenotípicas y aumentando la variabilidad genética",
            "Que las características son fijas y no pueden recombinarse entre generaciones",
            "Que la F2 siempre replica exactamente a los progenitores originales en proporción 3:1",
            "Que la recombinación genética solo ocurre en plantas, no en animales",
            "El Principio de Distribución Independiente establece que los alelos de un gen segregan independientemente de los de otro gen. Esto genera nuevas combinaciones de características en la descendencia, siendo la base molecular de la variabilidad genética.",
            difficulty="hard",
        ),
    ],

    # ── Módulo 10 — Tejidos y Sistemas del Cuerpo Humano ─────────────────────
    10: [
        q(
            "¿Cuáles son los cuatro tejidos básicos del cuerpo humano?",
            "Epitelial, conectivo, muscular y nervioso",
            "Muscular, óseo, nervioso y sanguíneo",
            "Epitelial, adiposo, cartilaginoso y óseo",
            "Conectivo, muscular, endocrino y linfático",
            "El módulo indica que los cuatro tejidos básicos del cuerpo humano son: epitelial, conectivo, muscular y nervioso.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la función principal del tejido epitelial según el módulo?",
            "Recubrir superficies internas y externas del cuerpo, protegiéndolo de daños mecánicos, microorganismos y pérdida de agua",
            "Producir células sanguíneas y transportar nutrientes por el organismo",
            "Conectar y sostener otros tejidos y órganos del cuerpo",
            "Generar impulsos eléctricos para la contracción muscular",
            "El módulo indica que el tejido epitelial recubre superficies internas y externas, protegiéndolas de daños mecánicos, microorganismos y pérdida de agua, con funciones adicionales de absorción y secreción.",
            difficulty="easy",
        ),
        q(
            "¿Cuál es la diferencia entre epitelio simple y epitelio estratificado?",
            "El epitelio simple tiene una sola capa de células; el estratificado tiene varias capas",
            "El simple tiene células cúbicas exclusivamente; el estratificado solo células planas",
            "El simple cubre únicamente órganos internos; el estratificado solo la piel",
            "El estratificado tiene membrana basal; el simple no la posee",
            "El módulo distingue: el epitelio simple tiene una sola capa de células (ej. endotelio), mientras que el estratificado tiene varias capas de células (ej. epidermis).",
            difficulty="medium",
        ),
        q(
            "¿Qué componentes le otorgan dureza al tejido óseo según el módulo?",
            "Oseína y fosfato tricálcico",
            "Condrocitos y fibras elásticas",
            "Osteína y calcio disuelto en agua",
            "Colágeno y fibras reticulares",
            "El módulo indica que la matriz del tejido óseo contiene oseína y fosfato tricálcico, lo que le otorga su característica dureza; las células óseas son los osteocitos.",
            difficulty="medium",
        ),
        q(
            "¿Por qué el tejido conectivo es considerado un 'medio de comunicación' entre tejidos y órganos según el módulo?",
            "Porque su matriz extracelular (con fibras colágenas, elásticas, agua e iones) proporciona soporte estructural y permite el intercambio de sustancias entre tejidos",
            "Porque contiene neuronas que transmiten señales eléctricas entre los distintos órganos",
            "Porque produce hormonas que regulan la comunicación química entre sistemas del cuerpo",
            "Porque es el único tejido que posee capilares sanguíneos para el transporte de nutrientes",
            "El módulo indica que el tejido conectivo sostiene y cohesiona otros tejidos y órganos, y que su matriz extracelular (fibras colágenas, elásticas, agua e iones) le otorga propiedades mecánicas y estructurales que facilitan la comunicación entre tejidos.",
            difficulty="hard",
        ),
    ],
}
