# Quizzes — Biología (Curso de Ingreso 2026)
# 10 módulos × 5 preguntas + 10 generales = 60 preguntas

def q(question, correct, wrong1, wrong2, wrong3, explanation, difficulty="medium"):
    return {
        "question": question,
        "options": [
            {"text": correct,  "is_correct": True},
            {"text": wrong1,   "is_correct": False},
            {"text": wrong2,   "is_correct": False},
            {"text": wrong3,   "is_correct": False},
        ],
        "explanation": explanation,
        "difficulty":  difficulty,
    }

QUESTIONS = {

# ── Módulo 1: Biodiversidad y características de los seres vivos ─────────────
1: [
    q("¿Cuáles son las propiedades más notables que distinguen a los seres vivos de la materia inerte?",
      "El movimiento, el crecimiento, la reproducción y el comportamiento",
      "El color, el tamaño, la textura y el peso",
      "La temperatura, la presión, el volumen y la masa",
      "La dureza, la conductividad, la solubilidad y el brillo",
      "El módulo señala que las propiedades más notables de los seres vivos son el movimiento, el crecimiento, la reproducción y el comportamiento, que permiten diferenciarlos de la materia inerte.",
      "easy"),

    q("¿Qué establece la teoría celular como concepto unificador en biología?",
      "Que todos los seres vivos están formados por células y sus productos, y que las reacciones químicas vitales ocurren dentro de ellas",
      "Que los seres vivos evolucionan a partir de formas más simples hacia formas más complejas",
      "Que la biodiversidad es el resultado de la adaptación al entorno físico",
      "Que los organismos multicelulares son más complejos que los unicelulares",
      "La teoría celular establece que la célula es la unidad morfológica y fisiológica de todos los organismos, y que todas las reacciones químicas vitales (liberación de energía y biosíntesis) ocurren dentro de las células.",
      "easy"),

    q("¿Qué papel cumple la evolución en la biodiversidad de los seres vivos?",
      "Es el factor que implica las transformaciones a lo largo del tiempo que originan las diversas formas de vida",
      "Es el mecanismo por el cual los seres vivos adquieren nuevas propiedades en cada generación de forma aleatoria",
      "Es un proceso que solo afecta a organismos unicelulares y no a los pluricelulares",
      "Es la capacidad de los seres vivos de reproducirse sin variación genética",
      "El módulo afirma que la evolución es un factor crucial que implica las transformaciones a lo largo del tiempo, originando las diversas formas de vida que conforman la biodiversidad.",
      "medium"),

    q("¿Cómo se relacionan las características de los seres vivos con su historia evolutiva?",
      "Todos los seres vivos comparten una historia evolutiva reflejada en sus características, que los diferencian de lo inanimado",
      "Cada especie tiene una historia evolutiva completamente independiente de las demás",
      "Las características de los seres vivos no tienen relación con la evolución, sino solo con el entorno inmediato",
      "La historia evolutiva solo se refleja en organismos complejos como los animales",
      "Según el módulo, todos los seres vivos comparten una historia evolutiva reflejada en sus características, las cuales los diferencian de lo inanimado.",
      "medium"),

    q("¿Por qué todos los campos de la Biología son relevantes para las ciencias de la salud como Medicina, Nutrición y Kinesiología?",
      "Porque están estrechamente relacionados con los conocimientos biológicos que ayudan a comprender enfermedades, el funcionamiento del cuerpo y las necesidades nutricionales",
      "Porque la biología estudia exclusivamente los organismos patógenos que causan enfermedades",
      "Porque la biología proporciona herramientas matemáticas para el diagnóstico clínico",
      "Porque todos los campos de la biología se centran en el estudio del ser humano",
      "El módulo indica que especialidades como Medicina, Nutrición, Enfermería, Kinesiología y Fisiatría están estrechamente relacionadas con la biología, ayudando a comprender enfermedades, el funcionamiento del cuerpo, las necesidades nutricionales y el sistema músculo-esquelético.",
      "hard"),
],

# ── Módulo 2: Composición química de los seres vivos ─────────────────────────
2: [
    q("¿Cuáles son las partículas subatómicas que forman el átomo?",
      "Protones, electrones y neutrones",
      "Fotones, bosones y quarks",
      "Iones, cationes y aniones",
      "Moléculas, compuestos y elementos",
      "El módulo indica que los átomos están formados por tres partículas subatómicas: protones, electrones y neutrones.",
      "easy"),

    q("¿Qué estudian los bioquímicos según el módulo?",
      "Las bases moleculares de la vida y las reacciones químicas que permiten a cada célula llevar a cabo sus funciones vitales",
      "Las propiedades físicas de los organismos vivos en su entorno natural",
      "La clasificación taxonómica de los seres vivos a nivel molecular",
      "Los procesos de evolución a nivel genético en poblaciones",
      "El módulo define que los bioquímicos estudian las bases moleculares de la vida y las reacciones químicas que permiten a cada célula llevar a cabo sus funciones vitales.",
      "easy"),

    q("¿Qué conceptos se abordan en la primera parte del Módulo 2 sobre composición química?",
      "Materia, Átomo, Protones, Electrones, Neutrones, Elementos Químicos y Tabla Periódica",
      "Células, Tejidos, Órganos, Sistemas y Organismos",
      "ADN, ARN, Proteínas, Lípidos e Hidratos de carbono",
      "Ecosistemas, Poblaciones, Comunidades y Biomas",
      "El módulo señala que en la primera parte se abordan: Materia, Átomo, Protones, Electrones, Neutrones, Elementos Químicos y Tabla Periódica.",
      "medium"),

    q("¿Por qué es esencial conocer los compuestos químicos de los seres vivos para comprender la vida?",
      "Porque permiten entender las propiedades de la materia organizada, sus cambios y las reacciones que posibilitan las funciones vitales",
      "Porque los compuestos químicos determinan el tamaño y la forma de cada organismo",
      "Porque solo mediante el conocimiento químico es posible clasificar a los seres vivos",
      "Porque los compuestos químicos son únicos para cada especie y no se comparten entre organismos",
      "Según el módulo, conocer los principales compuestos químicos, sus propiedades y cambios es esencial para comprender el fenómeno de la vida, ya que están organizados en estructuras con distintos niveles de organización.",
      "medium"),

    q("¿Cuál es la relación entre los niveles de organización de la materia y las funciones vitales de las células?",
      "Los compuestos están organizados en estructuras con distintos niveles de organización, y las reacciones entre ellos dentro de las células permiten llevar a cabo las funciones vitales",
      "Las funciones vitales ocurren solo a nivel de órganos y sistemas, no a nivel molecular",
      "Los niveles de organización de la materia son independientes de las funciones celulares",
      "Solo los compuestos inorgánicos participan en las reacciones que sostienen las funciones vitales",
      "El módulo explica que la materia está organizada en estructuras con distintos niveles de organización, y que las reacciones químicas dentro de las células (liberadoras de energía y biosintéticas) son las que permiten las funciones vitales.",
      "hard"),
],

# ── Módulo 3: Soluciones químicas y estequiometría ───────────────────────────
3: [
    q("¿Qué son las soluciones o disoluciones?",
      "Mezclas donde una sustancia está disuelta en otra, comunes en la vida cotidiana",
      "Compuestos puros formados por dos elementos químicos enlazados covalentemente",
      "Reacciones químicas que producen calor y luz como subproductos",
      "Sustancias sólidas que se forman al enfriar un líquido por debajo de su punto de fusión",
      "El módulo define que las disoluciones o soluciones son mezclas comunes en la vida diaria donde generalmente una sustancia está disuelta en otra, como el aire (gases) o las bebidas carbonatadas.",
      "easy"),

    q("¿Por qué es vital medir las concentraciones de electrolitos en los líquidos corporales?",
      "Porque los cambios en sus niveles pueden afectar gravemente la salud",
      "Porque los electrolitos determinan el color de la sangre y otros fluidos",
      "Porque regular los electrolitos permite controlar la temperatura corporal",
      "Porque su medición es necesaria para determinar el grupo sanguíneo",
      "El módulo señala que los líquidos corporales contienen agua y sustancias disueltas como iones (K+, Na+, Cl-, etc.) y que los cambios en sus niveles pueden afectar gravemente la salud, por lo que medir sus concentraciones es vital.",
      "easy"),

    q("¿Cuáles son ejemplos de soluciones presentes en la vida cotidiana según el módulo?",
      "El aire (mezcla de gases), bebidas carbonatadas, café o té, el océano y la tintura de yodo",
      "El aceite de cocina, la cera, la madera y las fibras textiles",
      "Las rocas volcánicas, el granito, la arcilla y la arena",
      "Los metales como el hierro, el aluminio, el cobre y el zinc",
      "El módulo presenta varios ejemplos: el aire es una mezcla de gases, las bebidas carbonatadas tienen CO₂ disuelto en agua, el café y el té se hacen disolviendo sustancias en agua, el océano tiene sales disueltas y la tintura de yodo es yodo en etanol.",
      "medium"),

    q("¿Cómo permiten la ósmosis y la diálisis regular los componentes de los líquidos corporales?",
      "Permitiendo el paso selectivo de sustancias a través de membranas semipermeables para equilibrar concentraciones",
      "Mediante reacciones químicas que descomponen los electrolitos en elementos más simples",
      "Generando calor que destruye las moléculas no deseadas en los líquidos corporales",
      "Aumentando la presión interna de las células para expulsar sustancias tóxicas",
      "El módulo menciona que la ósmosis y la diálisis permiten medir y regular las concentraciones de electrolitos en los líquidos corporales, siendo procesos basados en el paso selectivo de sustancias.",
      "medium"),

    q("¿Por qué el conocimiento de las soluciones y la estequiometría es relevante para las ciencias de la salud?",
      "Porque los líquidos corporales son soluciones complejas y el desequilibrio de sus componentes puede comprometer funciones vitales, siendo fundamental para diagnóstico y tratamiento",
      "Porque las reacciones estequiométricas son las únicas que ocurren en el cuerpo humano",
      "Porque la estequiometría permite calcular exactamente cuántas calorías necesita un organismo",
      "Porque solo las soluciones ácidas son compatibles con los líquidos corporales humanos",
      "El módulo vincula el conocimiento de soluciones con la salud: los líquidos corporales (sangre, linfa) son soluciones complejas con iones como K+, Na+, Cl-; su desequilibrio afecta gravemente la salud, por lo que el estudio de soluciones y sus concentraciones es clave en medicina.",
      "hard"),
],

# ── Módulo 4: Biomoléculas ────────────────────────────────────────────────────
4: [
    q("¿Cuáles son los cuatro grandes grupos de biomoléculas presentes en los seres vivos?",
      "Hidratos de carbono, proteínas, lípidos y ácidos nucleicos",
      "Vitaminas, minerales, agua y fibras",
      "Oxígeno, carbono, hidrógeno y nitrógeno",
      "Glucosa, aminoácidos, ácidos grasos y nucleótidos",
      "El módulo define que los componentes químicos de los seres vivos (biomoléculas) se clasifican en cuatro grandes grupos: hidratos de carbono, proteínas, lípidos y ácidos nucleicos.",
      "easy"),

    q("¿Qué son las biomoléculas?",
      "Los componentes químicos presentes en los seres vivos, comunes a todos los organismos",
      "Sustancias producidas exclusivamente por bacterias para defenderse de depredadores",
      "Moléculas inorgánicas que dan estructura a los huesos y tejidos mineralizados",
      "Compuestos que solo se encuentran en organismos pluricelulares complejos",
      "El módulo indica que todos los seres vivos están formados por los mismos componentes químicos llamados biomoléculas, que se clasifican en cuatro grandes grupos.",
      "easy"),

    q("¿Cuál es la relación que establece el módulo entre la composición química de los seres vivos y su diversidad de formas?",
      "A pesar de sus distintas formas, colores y tamaños, todos los seres vivos están formados por los mismos componentes químicos",
      "Cuanto más compleja es la forma de un organismo, mayor es la variedad de biomoléculas que lo componen",
      "Cada especie posee biomoléculas exclusivas que no se comparten con otras especies",
      "La diversidad de formas en los seres vivos se debe a que cada uno tiene una proporción única de los cuatro elementos químicos",
      "El módulo usa la analogía de las mesas de madera y sillas de plástico: aunque tienen distintas formas, están hechas del mismo material; igualmente, todos los seres vivos tienen distintas formas pero están formados por los mismos componentes químicos.",
      "medium"),

    q("¿Dónde se pueden encontrar biomoléculas en la vida diaria según el módulo?",
      "En alimentos como la leche, que contiene proteínas de alto valor nutricional por ser de origen animal",
      "Solo en laboratorios de bioquímica donde se sintetizan artificialmente",
      "Únicamente en el interior de las células, no en productos derivados de organismos",
      "En los minerales del suelo y en las rocas sedimentarias",
      "El módulo da como ejemplo la leche en la heladera, que contiene proteínas de alto valor nutricional porque son de origen animal, mostrando que las biomoléculas están presentes en alimentos cotidianos.",
      "medium"),

    q("¿Por qué los ácidos nucleicos son esenciales para la continuidad de la vida?",
      "Porque son las biomoléculas que almacenan y transmiten la información genética, permitiendo la reproducción y herencia de características",
      "Porque son la principal fuente de energía para las reacciones metabólicas celulares",
      "Porque forman las membranas celulares que protegen el contenido interno de la célula",
      "Porque actúan como catalizadores biológicos que aceleran todas las reacciones del organismo",
      "Los ácidos nucleicos (ADN y ARN) son las biomoléculas responsables de almacenar y transmitir la información genética, lo que permite la reproducción, el desarrollo y la herencia de características de una generación a la siguiente.",
      "hard"),
],

# ── Módulo 5: Generalidades de las células ───────────────────────────────────
5: [
    q("¿Cuál es la principal característica de la vida según el módulo sobre las células?",
      "Las células son la principal característica de la vida y la unidad anatómica y funcional de todos los seres vivos",
      "La reproducción sexual es la principal característica que define la vida",
      "La capacidad de moverse de forma autónoma es lo que define a un ser vivo",
      "El metabolismo energético es la característica esencial que distingue lo vivo de lo inerte",
      "El módulo afirma que un ser vivo es más que 'nace, crece, se reproduce y muere', y que las células son la principal característica de la vida y la unidad anatómica y funcional de todos los seres vivos.",
      "easy"),

    q("¿Qué forma tienen los eritrocitos y cuál es su función?",
      "Forma bicóncava; transportan gases y se mueven por capilares",
      "Forma esférica; producen anticuerpos para el sistema inmune",
      "Forma alargada con ramificaciones; transmiten impulsos nerviosos",
      "Forma cúbica; recubren la superficie interna del intestino",
      "El módulo indica que los eritrocitos (glóbulos rojos) en la sangre transportan gases y tienen una forma bicóncava que les permite moverse por los capilares.",
      "easy"),

    q("¿Cuál es la diferencia entre organismos unicelulares y pluricelulares?",
      "Los unicelulares están formados por una sola célula (como bacterias y levaduras), mientras que los pluricelulares están formados por muchas células (como animales y plantas)",
      "Los unicelulares son siempre microscópicos y los pluricelulares siempre son visibles a simple vista",
      "Los unicelulares no tienen núcleo mientras que todos los pluricelulares sí tienen",
      "Los unicelulares solo se reproducen asexualmente y los pluricelulares solo sexualmente",
      "El módulo distingue que los organismos pueden ser unicelulares, como bacterias y levaduras, o pluricelulares, como animales y plantas.",
      "medium"),

    q("¿Cómo se relaciona la forma de una célula con su función?",
      "Las formas celulares están estrechamente asociadas con sus funciones; por ejemplo, la forma bicóncava de los eritrocitos facilita el transporte por capilares, y la forma estrellada de las neuronas permite transmitir impulsos",
      "La forma celular es irrelevante para su función y solo varía según el organismo al que pertenece",
      "Todas las células tienen la misma forma esférica para optimizar el intercambio de nutrientes",
      "La forma celular solo cambia durante la división celular y no tiene relación con la función habitual",
      "El módulo establece la relación forma-función: los eritrocitos tienen forma bicóncava para moverse por capilares y transportar gases; las neuronas tienen forma estrellada con axón largo para transmitir impulsos nerviosos.",
      "medium"),

    q("¿Por qué la teoría celular es considerada un 'concepto unificador' en biología?",
      "Porque establece principios que aplican a todos los seres vivos sin excepción: todos están formados por células y en ellas ocurren las reacciones vitales",
      "Porque fue la primera teoría científica que unificó la física y la química bajo un solo marco teórico",
      "Porque permitió unificar la clasificación taxonómica de todos los organismos conocidos",
      "Porque demostró que todas las células del planeta tienen exactamente el mismo tamaño y composición",
      "La teoría celular es un concepto unificador porque sus principios aplican a la totalidad de los seres vivos: todos están formados por células y sus productos, y todas las reacciones químicas vitales ocurren dentro de las células.",
      "hard"),
],

# ── Módulo 6: Membrana plasmática ─────────────────────────────────────────────
6: [
    q("¿Cuál es la principal característica de la membrana plasmática?",
      "La permeabilidad selectiva, que permite el paso de ciertos componentes mientras otros no pueden atravesarla",
      "La rigidez absoluta que impide cualquier deformación de la célula",
      "La capacidad de generar energía mediante reacciones químicas en su superficie",
      "La transparencia total que permite observar el interior celular sin instrumentos",
      "El módulo indica que la principal característica de la membrana plasmática es la permeabilidad selectiva, que permite el paso de ciertos componentes mientras otros no pueden atravesarla.",
      "easy"),

    q("¿Qué funciones cumple la membrana plasmática?",
      "Mantener la presión osmótica, el reconocimiento celular, la fusión con otras células y actuar como barrera frente a agresiones externas",
      "Producir las proteínas necesarias para el funcionamiento celular",
      "Almacenar el material genético y controlar la expresión génica",
      "Realizar la fotosíntesis en células vegetales y la respiración en células animales",
      "El módulo señala que la membrana cumple funciones como mantener la presión osmótica, el reconocimiento celular, la fusión con otras células y facilitar el intercambio de moléculas, además de actuar como barrera frente a agresiones externas.",
      "easy"),

    q("¿Qué son los receptores químicos de la membrana plasmática?",
      "Estructuras de la membrana que se combinan con moléculas específicas, permitiendo a la célula detectar señales del entorno",
      "Canales que transportan activamente iones a través de la membrana usando energía",
      "Enzimas que degradan las moléculas que intentan atravesar la membrana sin autorización",
      "Proteínas que sintetizan lípidos para mantener la fluidez de la membrana",
      "El módulo indica que la membrana posee receptores químicos que se combinan con moléculas específicas, permitiendo a la célula reconocer e interactuar con señales del entorno.",
      "medium"),

    q("¿Por qué los estudios bioquímicos revelaron que la membrana plasmática es más compleja de lo que parece al microscopio óptico?",
      "Porque al microscopio óptico solo se ve una línea simple, pero bioquímicamente es una estructura con múltiples componentes y funciones complejas",
      "Porque la membrana cambia de composición química continuamente, haciendo imposible su análisis",
      "Porque la membrana plasmática es tan delgada que los métodos bioquímicos no pueden analizarla directamente",
      "Porque al microscopio óptico la membrana aparece como una estructura sólida, pero en realidad es un líquido",
      "El módulo señala que al observar una célula al microscopio óptico solo se distingue una línea que la delimita, pero los estudios bioquímicos revelan su complejidad estructural y funcional.",
      "medium"),

    q("¿Por qué la permeabilidad selectiva de la membrana plasmática es fundamental para el mantenimiento de la vida celular?",
      "Porque permite regular qué sustancias entran y salen de la célula, manteniendo el equilibrio interno (homeostasis) necesario para las funciones vitales",
      "Porque impide completamente el intercambio de sustancias, protegiendo el contenido celular de cualquier agente externo",
      "Porque permite que todas las moléculas del entorno entren libremente para que la célula tenga acceso a todos los nutrientes disponibles",
      "Porque genera la energía necesaria para las reacciones metabólicas al controlar el flujo de iones",
      "La permeabilidad selectiva es clave para la homeostasis celular: permite el ingreso de nutrientes y la salida de desechos, mientras bloquea sustancias dañinas, manteniendo las condiciones internas necesarias para que las reacciones vitales ocurran normalmente.",
      "hard"),
],

# ── Módulo 7: Citoplasma ─────────────────────────────────────────────────────
7: [
    q("¿Dónde se ubica el citoplasma en las células eucariotas?",
      "Entre la membrana plasmática y el núcleo",
      "Dentro del núcleo, rodeando el material genético",
      "En el exterior de la membrana plasmática",
      "Únicamente en los orgánulos especializados como las mitocondrias",
      "El módulo define que el citoplasma es una región clave en las células eucariotas, ubicada entre la membrana plasmática y el núcleo.",
      "easy"),

    q("¿Qué técnicas permitieron avanzar en la comprensión del citoplasma más allá de los microscopios ópticos?",
      "La microscopía electrónica y la biología molecular",
      "La resonancia magnética nuclear y la tomografía computarizada",
      "La espectroscopía de masas y la cromatografía",
      "La difracción de rayos X y la secuenciación de ADN",
      "El módulo indica que la comprensión del citoplasma avanzó gracias a técnicas sofisticadas de microscopía electrónica y biología molecular, que permitieron ver más allá de las células como simples recipientes llenos de fluidos.",
      "easy"),

    q("¿Cuál es la diferencia entre el citoplasma de células procariotas y eucariotas según el módulo?",
      "Ambos tienen citoplasma, pero sus componentes son diferentes",
      "Solo las células eucariotas tienen citoplasma; las procariotas no poseen esta estructura",
      "El citoplasma de los procariotas está dividido por membranas internas, mientras que el de los eucariotas no",
      "Solo las células procariotas tienen citoplasma funcional; en las eucariotas es vestigial",
      "El módulo señala que aunque las células procariotas también tienen citoplasma, sus componentes son diferentes a los de las células eucariotas.",
      "medium"),

    q("¿Cómo se observa el citoplasma en imágenes de microscopía óptica de tejidos?",
      "Como una zona clara entre la membrana y el núcleo, delimitada por las membranas plasmáticas, con los núcleos como estructuras redondeadas y oscuras",
      "Como una masa densa y oscura que ocupa la mayor parte del volumen celular",
      "Como una red de filamentos brillantes que conectan la membrana con el núcleo",
      "Como pequeñas vesículas dispersas alrededor del núcleo celular",
      "El módulo describe que en imágenes de tejidos (raíz de cebolla, vesícula biliar humana) el citoplasma aparece como una zona clara entre la membrana y el núcleo, delimitada por las membranas plasmáticas, con núcleos como estructuras redondeadas y oscuras.",
      "medium"),

    q("¿Por qué la comprensión del citoplasma como algo más que 'un recipiente lleno de fluidos' fue un avance significativo en biología celular?",
      "Porque reveló que el citoplasma contiene estructuras organizadas (orgánulos y citoesqueleto) con funciones específicas que coordinan las actividades celulares",
      "Porque demostró que el citoplasma puede sobrevivir de forma independiente fuera de la célula",
      "Porque permitió descubrir que el citoplasma es el único sitio donde ocurre la síntesis de ADN",
      "Porque demostró que el citoplasma no tiene ninguna función en las células procariotas",
      "Gracias a la microscopía electrónica y la biología molecular, se descubrió que el citoplasma no es solo un fluido, sino que contiene el citosol y orgánulos con funciones específicas que coordinan las actividades metabólicas y estructurales de la célula.",
      "hard"),
],

# ── Módulo 8: Núcleo celular ──────────────────────────────────────────────────
8: [
    q("¿Cuál es la característica principal que diferencia las células eucariotas de las procariotas?",
      "La existencia del núcleo, que almacena el ADN (genoma) de la célula",
      "La presencia de mitocondrias para producir energía mediante respiración celular",
      "El mayor tamaño de las células eucariotas respecto a las procariotas",
      "La capacidad de las células eucariotas de realizar fotosíntesis",
      "El módulo indica que la existencia del núcleo es la característica principal que diferencia las células eucariotas de las procariotas; el término eucariota significa 'núcleo verdadero' (del griego eu: bien, karyon: núcleo).",
      "easy"),

    q("¿Qué es el genoma?",
      "Todo el ADN de la célula almacenado en el núcleo, que constituye la base de datos de toda la información genética del organismo",
      "El conjunto de proteínas que regulan la expresión de los genes en una célula",
      "El ARN mensajero producido durante la transcripción para sintetizar proteínas",
      "El conjunto de cromosomas visibles durante la división celular",
      "El módulo define que en el núcleo se almacena todo el ADN de la célula, denominado genoma, el cual constituye la base de datos de toda la información genética del organismo.",
      "easy"),

    q("¿Cuáles son las funciones principales del núcleo celular?",
      "Ser el depósito de la información genética y el centro de control de la expresión del material genético; en él ocurren la replicación y la transcripción del ADN",
      "Producir la energía necesaria para las reacciones celulares mediante la respiración aeróbica",
      "Sintetizar lípidos y carbohidratos para las membranas y el metabolismo energético",
      "Regular el paso de sustancias hacia el interior y exterior de la célula",
      "El módulo establece que el núcleo es el depósito de la información genética y el centro de control de su expresión, y que en él ocurren la replicación y la transcripción del ADN.",
      "medium"),

    q("¿Por qué la replicación y la transcripción del ADN se separan del resto del metabolismo celular en las células eucariotas?",
      "Gracias a la envoltura nuclear, que delimita el núcleo y separa estas actividades del resto del metabolismo celular",
      "Porque ocurren a temperaturas diferentes al resto de las reacciones metabólicas",
      "Porque requieren un pH muy ácido que sería incompatible con el citoplasma",
      "Porque solo pueden realizarse en ausencia de oxígeno, al contrario del metabolismo",
      "El módulo señala que la replicación y transcripción del ADN ocurren en el núcleo, separándose del resto del metabolismo celular gracias a la envoltura nuclear.",
      "medium"),

    q("¿Por qué el núcleo puede considerarse el 'centro de control' de la célula?",
      "Porque almacena toda la información genética (genoma) y controla la expresión génica, determinando qué proteínas se producen y regulando así todas las funciones celulares",
      "Porque es el orgánulo más grande de la célula y por eso domina físicamente todas las demás estructuras",
      "Porque genera las señales eléctricas que coordinan los movimientos del citoesqueleto",
      "Porque es el único orgánulo capaz de dividirse y por eso determina cuándo se divide la célula",
      "El núcleo es el centro de control porque contiene el genoma y regula la expresión génica: al controlar qué genes se transcriben y, por tanto, qué proteínas se producen, regula indirectamente todas las funciones metabólicas y estructurales de la célula.",
      "hard"),
],

# ── Módulo 9: Reproducción celular ───────────────────────────────────────────
9: [
    q("¿Cuáles son los dos tipos principales de células en organismos pluricelulares?",
      "Somáticas (forman el cuerpo, se dividen por mitosis) y germinales (participan en la reproducción)",
      "Eucariotas (con núcleo) y procariotas (sin núcleo)",
      "Vegetativas (realizan fotosíntesis) y reproductivas (forman semillas)",
      "Diploides (2n cromosomas) y haploides (n cromosomas)",
      "El módulo distingue dos tipos de células en organismos pluricelulares: somáticas, que forman el cuerpo y se dividen por mitosis, y germinales, que participan en la reproducción.",
      "easy"),

    q("¿Qué ocurre durante la división celular?",
      "La célula distribuye su material genético (ADN) entre dos células hijas, que luego pueden crecer y dividirse",
      "La célula fusiona su ADN con el de otra célula para formar una célula con mayor material genético",
      "La célula destruye su núcleo y forma dos núcleos nuevos sin distribuir el ADN",
      "El ADN se replica pero permanece en la misma célula sin dividirse",
      "El módulo define que las células se reproducen a través de la división celular, distribuyendo su material genético (ADN) entre dos células hijas, que luego pueden crecer y dividirse.",
      "easy"),

    q("¿Cuál es la diferencia entre mitosis y meiosis según el módulo?",
      "Las células somáticas se dividen por mitosis; las células germinales participan en la reproducción a través de la meiosis, que produce células con la mitad del material genético",
      "La mitosis produce cuatro células hijas y la meiosis produce solo dos",
      "La mitosis ocurre solo en organismos unicelulares y la meiosis solo en pluricelulares",
      "La mitosis genera variabilidad genética y la meiosis produce copias idénticas",
      "El módulo indica que las células somáticas se dividen por mitosis creando dos células hijas con la misma dotación genética, mientras que las germinales intervienen en la reproducción a través de procesos que producen células con la mitad del material genético (meiosis).",
      "medium"),

    q("¿Cómo contribuye la división celular al crecimiento y reparación de tejidos?",
      "En organismos pluricelulares como plantas y animales, la división celular facilita el crecimiento y la reparación de tejidos mediante la producción de nuevas células",
      "La división celular solo se produce durante el desarrollo embrionario y no en organismos adultos",
      "La división celular genera variabilidad genética que permite adaptar los tejidos al entorno",
      "En plantas, la división celular ocurre solo en las raíces; en animales, solo en la médula ósea",
      "El módulo señala que en organismos pluricelulares como plantas y animales, la división celular facilita el crecimiento y la reparación de tejidos.",
      "medium"),

    q("¿Por qué la capacidad de autoreproducirse es considerada una característica esencial de las células y los seres vivos?",
      "Porque permite la continuidad de la vida: los organismos unicelulares forman colonias y los pluricelulares crecen y reparan tejidos mediante la división celular que distribuye el material genético",
      "Porque sin reproducción los organismos no podrían obtener energía del ambiente para sobrevivir",
      "Porque la reproducción es el único proceso que diferencia a las células vivas de las estructuras químicas complejas",
      "Porque la autoreproducción garantiza que cada célula hija tenga exactamente el doble de ADN que la célula madre",
      "El módulo afirma que la autoreproducción es esencial: permite que organismos unicelulares formen colonias a partir de una sola célula, y que los pluricelulares crezcan y reparen tejidos. Sin esta capacidad, la vida no podría perpetuarse.",
      "hard"),
],

# ── Módulo 10: Salud y ambiente ───────────────────────────────────────────────
10: [
    q("¿Cuál es uno de los conceptos más importantes actualmente en ecología y a nivel mundial?",
      "El concepto de 'Ambiente', debido a la crisis ambiental global",
      "El concepto de 'Evolución', porque explica el origen de todas las especies",
      "El concepto de 'Célula', porque es la unidad básica de todos los seres vivos",
      "El concepto de 'Biodiversidad', porque cuantifica las especies existentes",
      "El módulo señala que uno de los conceptos más importantes actualmente en ecología y a nivel mundial es el de 'Ambiente', debido a la crisis ambiental global.",
      "easy"),

    q("¿Qué actividades humanas deterioran las condiciones ambientales según el módulo?",
      "Actividades que provocan contaminación, degradación y sobrexplotación de los entornos naturales",
      "Únicamente las actividades industriales de gran escala en países desarrollados",
      "Solo las actividades agrícolas intensivas en regiones tropicales",
      "Exclusivamente la deforestación en zonas de selva tropical",
      "El módulo indica que las condiciones ambientales están deterioradas globalmente por actividades humanas que provocan contaminación, degradación y sobrexplotación de los entornos naturales.",
      "easy"),

    q("¿Cómo impacta el deterioro ambiental en la salud humana según el módulo?",
      "Porque los ecosistemas sostienen la vida en el planeta, y su deterioro puede poner en peligro servicios esenciales como alimento, agua, aire puro, abrigo y clima constante",
      "El deterioro ambiental solo afecta la salud de animales silvestres, no la de los seres humanos",
      "El impacto es exclusivamente económico, reduciendo los recursos disponibles para el sistema de salud",
      "Solo afecta la salud mediante enfermedades infecciosas que emergen en zonas deforestadas",
      "El módulo explica que los ecosistemas sostienen la vida en el planeta, y si se deterioran gravemente, los servicios que brindan (alimento, agua, aire puro, abrigo y clima constante) podrían verse en peligro, afectando necesidades humanas básicas.",
      "medium"),

    q("¿Por qué las relaciones entre cambios ambientales y salud humana son complejas?",
      "Porque son de naturaleza indirecta y dependiente de diversas fuerzas, haciendo difícil establecer causalidades directas",
      "Porque los efectos del ambiente en la salud son inmediatos y no permiten tiempo para estudiarlos",
      "Porque solo afectan a poblaciones en regiones geográficas específicas y no a nivel global",
      "Porque los seres humanos tienen mecanismos inmunológicos que los aíslan completamente de los cambios ambientales",
      "El módulo señala que las relaciones entre cambios ambientales y salud humana son complejas debido a su naturaleza indirecta y dependiente de diversas fuerzas.",
      "medium"),

    q("¿Cuál es la relación fundamental entre ecosistemas, actividades humanas y salud según el módulo?",
      "Las actividades humanas deterioran los ecosistemas que sostienen la vida, comprometiendo servicios esenciales para la salud humana en un ciclo complejo de interdependencias",
      "Los ecosistemas son independientes de las actividades humanas y la salud depende solo de factores genéticos",
      "La salud humana mejora cuando los ecosistemas se deterioran, porque el progreso industrial genera mejores condiciones sanitarias",
      "Solo los ecosistemas acuáticos tienen impacto directo en la salud humana a través del agua potable",
      "El módulo establece que las actividades humanas deterioran los ecosistemas; estos ecosistemas sostienen la vida proveyendo servicios esenciales (alimento, agua, aire, clima); su pérdida compromete necesidades básicas humanas. Esta es la relación compleja entre ambiente y salud.",
      "hard"),
],

# ── Preguntas generales (simulacro) ──────────────────────────────────────────
0: [
    q("¿Qué tienen en común todos los seres vivos a nivel molecular, independientemente de su diversidad de formas?",
      "Están formados por los mismos componentes químicos: biomoléculas como hidratos de carbono, proteínas, lípidos y ácidos nucleicos",
      "Tienen exactamente el mismo número de células y cromosomas",
      "Comparten la misma secuencia de ADN en un 100% con todos los demás organismos",
      "Producen los mismos metabolitos y desechos en sus reacciones químicas",
      "A pesar de la enorme diversidad de formas, todos los seres vivos comparten los mismos tipos de biomoléculas (hidratos de carbono, proteínas, lípidos y ácidos nucleicos), lo cual refleja su historia evolutiva común.",
      "medium"),

    q("¿Cuál es la diferencia fundamental entre células procariotas y eucariotas?",
      "Las eucariotas tienen núcleo verdadero (envoltura nuclear) donde almacenan el ADN; las procariotas no tienen núcleo delimitado por membrana",
      "Las procariotas son siempre más pequeñas que las eucariotas y no tienen citoplasma",
      "Las eucariotas no tienen pared celular, mientras que todas las procariotas sí la tienen",
      "Las procariotas pueden reproducirse y las eucariotas no tienen capacidad de división",
      "La diferencia fundamental es la presencia de núcleo verdadero (envoltura nuclear) en las eucariotas, donde se almacena el ADN organizado en el genoma, mientras que en las procariotas el ADN está en el citoplasma sin membrana que lo delimite.",
      "medium"),

    q("¿Qué función tienen los ácidos nucleicos en la reproducción celular?",
      "Almacenan la información genética que se replica y distribuye entre las células hijas durante la división celular",
      "Proporcionan la energía necesaria para que la célula se divida",
      "Forman la membrana que se divide durante la citocinesis",
      "Actúan como señales químicas que inician el proceso de división",
      "Los ácidos nucleicos (ADN) son las biomoléculas que almacenan la información genética. Durante la división celular, el ADN se replica y se distribuye equitativamente entre las dos células hijas, asegurando que cada una reciba la información completa.",
      "hard"),

    q("¿Por qué la membrana plasmática y la envoltura nuclear son esenciales para la organización de la célula eucariota?",
      "La membrana plasmática delimita la célula y regula el intercambio con el entorno; la envoltura nuclear separa el genoma del citoplasma, protegiendo la información genética",
      "Ambas membranas producen energía mediante el transporte de electrones a lo largo de su superficie",
      "La membrana plasmática sintetiza proteínas y la envoltura nuclear sintetiza lípidos para el metabolismo",
      "Ambas membranas son impermeables y evitan completamente el intercambio de sustancias",
      "La membrana plasmática define los límites de la célula y actúa como barrera selectiva hacia el entorno. La envoltura nuclear separa el compartimento donde ocurren la replicación y transcripción del ADN del resto del metabolismo celular.",
      "hard"),

    q("¿Cómo se relacionan la teoría celular y el concepto de biodiversidad?",
      "La teoría celular unifica a todos los seres vivos al establecer que todos están formados por células, explicando así la base común de la biodiversidad a pesar de la diversidad de formas",
      "La teoría celular explica por qué existen tantas especies diferentes, ya que cada especie tiene un tipo único de célula",
      "La biodiversidad contradice la teoría celular porque existen organismos que no están formados por células",
      "La teoría celular y la biodiversidad son conceptos independientes sin relación entre sí",
      "La teoría celular establece que todos los seres vivos están formados por células (unidad común), lo cual explica la base molecular compartida de la biodiversidad. A pesar de la enorme diversidad de formas de vida, todos comparten esta unidad fundamental.",
      "hard"),

    q("¿Cuál es la relación entre los electrolitos de los líquidos corporales y las funciones celulares?",
      "Los electrolitos (K+, Na+, Cl-) son solutos de los líquidos corporales que regulan la presión osmótica y son esenciales para el funcionamiento celular; su desequilibrio puede ser fatal",
      "Los electrolitos solo funcionan como fuente de energía para las células musculares",
      "Los electrolitos son exclusivamente producidos por las células renales y no tienen función en otras células",
      "Los electrolitos solo son importantes en células nerviosas y no en el resto del organismo",
      "Los líquidos corporales son soluciones que contienen electrolitos (K+, Na+, Cl-, Mg2+, etc.). Estos regulan la presión osmótica de las células, permiten la transmisión de impulsos nerviosos y son fundamentales para numerosas reacciones metabólicas. Su desequilibrio puede afectar gravemente la salud.",
      "medium"),

    q("¿Qué tienen en común la mitosis en células somáticas y la reproducción de organismos unicelulares?",
      "En ambos casos la división celular distribuye el material genético entre células hijas, permitiendo la continuidad y multiplicación de la vida",
      "En ambos casos se produce variabilidad genética para favorecer la adaptación al entorno",
      "Ambos procesos requieren la participación de células germinales especializadas",
      "En ambos casos se produce reducción del material genético a la mitad en cada división",
      "Tanto en la mitosis de células somáticas como en la reproducción de organismos unicelulares, la división celular distribuye el ADN entre células hijas. En unicelulares esto forma colonias; en pluricelulares permite crecer y reparar tejidos. La continuidad de la información genética es el denominador común.",
      "medium"),

    q("¿Cómo se vinculan los conceptos de membrana plasmática y soluciones químicas en el contexto celular?",
      "La membrana plasmática regula mediante permeabilidad selectiva el intercambio de solutos entre el interior celular (citosol) y el medio extracelular, siendo clave para la ósmosis",
      "Las soluciones químicas disuelven la membrana plasmática para permitir el paso de nutrientes",
      "La membrana plasmática produce las soluciones salinas que componen el citosol",
      "Las soluciones ácidas del entorno destruyen la membrana plasmática, obligando a la célula a regenerarla",
      "La membrana plasmática, gracias a su permeabilidad selectiva, regula el paso de solutos entre el citosol (solución interna) y el medio extracelular. Este control es fundamental para la ósmosis: si las concentraciones de solutos no están equilibradas, el agua entra o sale de la célula por ósmosis.",
      "hard"),

    q("¿Por qué el deterioro ambiental puede afectar la biodiversidad y, en consecuencia, la salud humana?",
      "Porque los ecosistemas diversos sostienen los servicios ambientales (agua, alimento, aire) que son necesidades básicas humanas; su pérdida compromete la supervivencia",
      "Porque la biodiversidad solo tiene valor estético y el deterioro ambiental reduce el turismo",
      "Porque la biodiversidad genera los fármacos que usa la medicina moderna y su pérdida encarece los tratamientos",
      "Porque el deterioro ambiental afecta solo a las especies salvajes, no a las domesticadas que usa el ser humano",
      "La biodiversidad sostiene el funcionamiento de los ecosistemas que proveen servicios esenciales: agua potable, alimentos, aire limpio y regulación del clima. El deterioro ambiental reduce la biodiversidad, debilita los ecosistemas y compromete estos servicios, afectando directamente la salud y supervivencia humana.",
      "hard"),

    q("¿Cuál es el hilo conductor que une los conceptos de célula, biomoléculas, reproducción y ambiente en biología?",
      "Todos forman parte de la comprensión integral de la vida: desde la base molecular (biomoléculas) hasta la organización celular, la continuidad (reproducción) y la relación con el entorno (ambiente)",
      "Son conceptos completamente independientes que se estudian en disciplinas científicas separadas",
      "El único hilo conductor es el ADN, ya que es la única molécula presente en todos estos niveles",
      "Solo están relacionados en organismos complejos; en bacterias y virus son conceptos independientes",
      "La biología estudia la vida en múltiples niveles integrados: las biomoléculas forman las células, las células se reproducen perpetuando la vida, y los organismos interactúan con el ambiente. Estos niveles son interdependientes: sin biomoléculas no hay célula; sin reproducción no hay continuidad; sin ambiente sostenible, no hay vida posible.",
      "hard"),
],
}
