def q(question, correct, wrong1, wrong2, wrong3, explanation, difficulty="medium"):
    return {
        "question": question,
        "options": [
            {"text": correct, "is_correct": True},
            {"text": wrong1,  "is_correct": False},
            {"text": wrong2,  "is_correct": False},
            {"text": wrong3,  "is_correct": False},
        ],
        "explanation": explanation,
        "difficulty":  difficulty,
    }

QUESTIONS = {
    1: [
        q("¿Qué significa etimológicamente la palabra 'filosofía'?",
          "Amor a la sabiduría (philos + sophia)",
          "Búsqueda de la verdad (philia + aletheia)",
          "Conocimiento del ser (gnosis + ontos)",
          "Estudio de la razón (logos + nous)",
          "Filosofía deriva del griego philos (amigo, amante) y sophia (sabiduría), por lo que significa literalmente 'amor a la sabiduría' o 'amistad con el saber'.",
          "easy"),
        q("¿Cuál es la diferencia fundamental entre mythos y lógos según el módulo?",
          "El mythos explica el mundo mediante relatos de dioses y héroes, mientras el lógos lo hace mediante argumentos racionales y causas naturales",
          "El mythos es propio de la filosofía, el lógos de la religión",
          "El lógos es anterior al mythos en la historia del pensamiento griego",
          "El mythos y el lógos son formas equivalentes de conocimiento para los griegos",
          "El mythos apela a fuerzas sobrenaturales para explicar el origen del mundo; el lógos busca explicaciones mediante la razón y causas naturales. El paso del mythos al lógos marca el origen de la filosofía.",
          "easy"),
        q("¿Por qué la polis griega fue condición de posibilidad para el surgimiento de la filosofía?",
          "Porque la vida en la polis exigía argumentar y debatir públicamente, lo que fomentó el pensamiento racional y crítico",
          "Porque la polis financiaba a los filósofos con fondos del Estado",
          "Porque la polis eliminó los mitos y la religión, liberando espacio para la razón",
          "Porque la polis era el único lugar donde se podían leer textos filosóficos",
          "La polis griega generó un espacio de deliberación pública donde los ciudadanos debían justificar sus posiciones con argumentos. Esta práctica del diálogo y la argumentación fue el suelo cultural que hizo posible la filosofía.",
          "medium"),
        q("¿En qué consiste la ironía socrática como método filosófico?",
          "Sócrates fingía ignorancia para llevar a su interlocutor a contradecirse y reconocer que no sabía lo que creía saber",
          "Sócrates usaba el sarcasmo para ridiculizar a sus adversarios en el ágora",
          "Sócrates afirmaba conocer la verdad y la comunicaba directamente a sus discípulos",
          "Sócrates evitaba el diálogo directo y prefería la escritura para transmitir su pensamiento",
          "La ironía socrática (del griego eironeía: disimulo) consistía en que Sócrates se presentaba como ignorante para que el interlocutor expusiera sus ideas y luego, mediante preguntas, lo conducía a descubrir las contradicciones de su propio saber.",
          "medium"),
        q("Según el módulo, ¿cuáles son las funciones de la filosofía según la perspectiva crítica presentada?",
          "Incomodar, entristecer y criticar los saberes y prácticas naturalizadas de la sociedad",
          "Consolar, orientar y brindar certezas a quienes enfrentan problemas existenciales",
          "Sistematizar el conocimiento científico y otorgarle fundamentos sólidos",
          "Preservar la tradición cultural y transmitir los valores establecidos de generación en generación",
          "El módulo señala que la filosofía tiene una función crítica: incomodar al cuestionar lo que se da por sentado, entristecer al mostrar las contradicciones de la realidad, y criticar los saberes establecidos para abrir nuevas posibilidades de pensamiento.",
          "hard"),
    ],
    2: [
        q("¿Qué distingue la episteme de la doxa en la filosofía griega?",
          "La episteme es conocimiento verdadero y fundamentado; la doxa es opinión sin fundamento racional sólido",
          "La doxa es el conocimiento científico y la episteme el conocimiento popular",
          "La episteme refiere al conocimiento sensorial; la doxa al conocimiento intelectual",
          "Ambos términos son sinónimos en la tradición filosófica griega",
          "En griego, doxa significa opinión (conocimiento sin justificación rigurosa) y episteme significa ciencia o conocimiento verdadero, fundamentado y necesario. La epistemología estudia las condiciones y límites de la episteme.",
          "easy"),
        q("¿De qué se ocupa la epistemología como disciplina filosófica?",
          "Del estudio de los tipos de conocimiento, sus fundamentos, alcances y límites",
          "Del estudio de los seres vivos y su relación con el entorno natural",
          "Del análisis de las estructuras lógicas del lenguaje formal",
          "De la reflexión sobre los valores morales y las normas de conducta",
          "La epistemología (del griego episteme: conocimiento verdadero, y logos: estudio) es la disciplina filosófica que investiga la naturaleza, el origen, la validez y los límites del conocimiento humano.",
          "easy"),
        q("¿Qué transformación representó la ciencia moderna del siglo XVII respecto al conocimiento anterior?",
          "La matematización de la naturaleza y el método experimental reemplazaron la autoridad de Aristóteles y la escolástica",
          "La ciencia moderna recuperó el conocimiento mítico griego como fundamento del saber",
          "La ciencia moderna limitó el conocimiento al ámbito de la teología y la metafísica",
          "La ciencia moderna rechazó el uso de la razón y priorizó la experiencia sensorial sin método",
          "Con Galileo, Bacon y Descartes, la ciencia moderna estableció que la naturaleza es un libro escrito en lenguaje matemático y que el conocimiento válido requiere método experimental, abandonando la física aristotélica.",
          "medium"),
        q("¿Qué plantea la hermenéutica como problema epistemológico?",
          "Que todo conocimiento implica una interpretación y que no existe acceso neutro a la realidad",
          "Que la hermenéutica es un método para traducir textos del griego al latín",
          "Que el conocimiento objetivo es posible si se eliminan los prejuicios del intérprete",
          "Que solo los textos religiosos requieren interpretación; los científicos son transparentes",
          "La hermenéutica plantea que comprender es siempre interpretar desde un horizonte cultural e histórico. No hay conocimiento sin interpretación, lo que cuestiona el ideal de objetividad absoluta de la ciencia moderna.",
          "medium"),
        q("¿Cómo opera la dialéctica hegeliana en la producción de conocimiento?",
          "Una tesis afirma algo, la antítesis la niega, y la síntesis supera ambas conservando lo positivo de cada una en un nivel superior",
          "La dialéctica hegeliana consiste en el debate entre dos interlocutores que llegan a un acuerdo por votación",
          "La tesis y la antítesis son irreconciliables; la síntesis simplemente elige una de las dos",
          "La dialéctica hegeliana afirma que el conocimiento es estático y no puede desarrollarse",
          "Para Hegel, el pensamiento avanza dialécticamente: una tesis genera su propia negación (antítesis) y ambas son superadas (Aufhebung) en una síntesis que conserva y eleva lo verdadero de cada momento.",
          "hard"),
    ],
    3: [
        q("¿Qué consigna se encontraba en el oráculo de Delfos y cuál es su relación con la Antropología Filosófica?",
          "'Conócete a ti mismo': expresa que el objeto de la Antropología Filosófica es el conocimiento del ser humano por sí mismo",
          "'Nada en exceso': indica que la moderación es el principio rector de la filosofía griega",
          "'El hombre es la medida de todas las cosas': define la antropología como estudio de las relaciones humanas",
          "'Sé virtuoso': establece la ética como fundamento del autoconocimiento en Grecia",
          "La inscripción 'Conócete a ti mismo' en el templo de Apolo en Delfos sintetiza el programa de la Antropología Filosófica: la reflexión sistemática sobre la naturaleza, el sentido y los límites del ser humano.",
          "easy"),
        q("¿Cómo definió Aristóteles al ser humano en su concepción política?",
          "Como 'zóon politikón' (animal político), es decir, un ser que solo se realiza plenamente en la vida en comunidad",
          "Como un ser racional aislado que funda la sociedad por contrato voluntario",
          "Como un ser espiritual cuya verdadera naturaleza trasciende la vida comunitaria",
          "Como un animal entre otros, sin diferencia esencial respecto al resto de la naturaleza",
          "Para Aristóteles, el ser humano es por naturaleza un 'zóon politikón': solo fuera de la polis puede vivir una bestia o un dios. La vida política es constitutiva de la naturaleza humana, no algo añadido.",
          "easy"),
        q("¿En qué se diferencia la concepción cristiana del hombre de la concepción griega clásica?",
          "El cristianismo introduce un alma inmortal creada por Dios y la idea de pecado original, mientras que los griegos concebían al hombre como ser natural y político sin dimensión sobrenatural",
          "El cristianismo valora más el cuerpo que el alma, a diferencia del dualismo platónico",
          "La concepción griega afirma que el hombre fue creado por dioses, mientras el cristianismo lo ve como producto de la evolución natural",
          "Ambas concepciones son idénticas en su visión de la relación cuerpo-alma",
          "La antropología cristiana incorpora el alma inmortal creada por Dios a imagen divina, la caída por el pecado original y la necesidad de redención. Esto contrasta con la visión griega del hombre como ser natural y político.",
          "medium"),
        q("¿Qué lugar ocupa la razón en la concepción del hombre durante la Ilustración?",
          "La razón es la facultad que define y distingue al ser humano, y su ejercicio autónomo es la vía hacia la libertad y el progreso",
          "La razón es secundaria respecto a la fe religiosa, que sigue siendo el fundamento del conocimiento",
          "La Ilustración rechaza la razón individual y promueve la obediencia a la tradición",
          "La razón ilustrada se limita al ámbito científico y excluye los problemas éticos y políticos",
          "La Ilustración (Aufklärung) postula que el ser humano debe atreverse a usar su propia razón (sapere aude, Kant) sin tutelas religiosas ni políticas. La razón autónoma es el instrumento del progreso moral y político.",
          "medium"),
        q("¿Qué significa la afirmación de Sartre 'la existencia precede a la esencia' en el marco del existencialismo?",
          "El ser humano no tiene una naturaleza fija predeterminada: primero existe y luego se define a sí mismo mediante sus elecciones y acciones",
          "El ser humano tiene una esencia divina que antecede a su existencia material en el mundo",
          "La existencia física del cuerpo determina completamente la esencia espiritual del individuo",
          "Sartre afirma que la esencia humana está determinada biológicamente antes del nacimiento",
          "A diferencia de un objeto cuya esencia precede a su fabricación, el ser humano para Sartre no tiene naturaleza dada de antemano: existe primero y luego construye su esencia a través de la libertad y la responsabilidad de sus elecciones.",
          "hard"),
    ],
    4: [
        q("¿Cómo describe Hobbes el estado de naturaleza previo al contrato social?",
          "Como una guerra de todos contra todos, donde la vida del hombre es solitaria, pobre, desagradable, brutal y breve",
          "Como un estado de paz y cooperación natural donde los hombres conviven armónicamente",
          "Como una sociedad primitiva justa regida por la ley de la razón natural",
          "Como un estado de inocencia similar al paraíso bíblico, corrompido por la propiedad privada",
          "Para Hobbes, en el estado de naturaleza los hombres son iguales en capacidad para hacerse daño, lo que genera una guerra de todos contra todos. Por eso ceden su libertad al soberano (Leviatán) mediante el contrato social.",
          "easy"),
        q("¿Qué sostiene Rousseau sobre el origen de la desigualdad entre los hombres?",
          "La desigualdad no es natural sino resultado de la sociedad civil y especialmente de la propiedad privada",
          "La desigualdad es natural e inevitable porque los hombres nacen con distintas capacidades",
          "La desigualdad surge del contrato social que establece jerarquías legítimas entre los ciudadanos",
          "Rousseau considera que la desigualdad existía en el estado de naturaleza antes que la sociedad",
          "Rousseau sostiene que el hombre es naturalmente bueno (buen salvaje) y que es la sociedad, especialmente la institución de la propiedad privada, la que introduce la desigualdad y la corrupción moral.",
          "easy"),
        q("¿Cuál es el aporte central de Locke a la teoría política en relación con los derechos naturales?",
          "Los hombres poseen derechos naturales (vida, libertad y propiedad) anteriores al Estado, que el gobierno debe proteger y no puede violar legítimamente",
          "Locke sostiene que el soberano es la fuente de todos los derechos y puede revocarlos a discreción",
          "Los derechos solo existen dentro del Estado y son otorgados por el contrato social, sin existencia previa",
          "Locke coincide con Hobbes en que los ciudadanos deben obedecer al soberano incluso si viola sus libertades",
          "Locke argumenta que los derechos a la vida, la libertad y la propiedad son anteriores y superiores al Estado. El gobierno es un fideicomisario que los ciudadanos pueden revocar si los viola, justificando el derecho a la resistencia.",
          "medium"),
        q("¿Qué entiende Marx por alienación del trabajador?",
          "El trabajador se separa del producto de su trabajo, de su actividad productiva, de su especie y de otros hombres, convirtiéndose en un ser extraño a sí mismo bajo el capitalismo",
          "La alienación es un estado mental de confusión filosófica sin relación con las condiciones materiales de trabajo",
          "Marx usa alienación para describir el estado de felicidad del trabajador que acepta su condición libremente",
          "La alienación refiere únicamente a la separación del trabajador respecto a la religión y la tradición",
          "Para Marx, en el capitalismo el trabajador aliena su fuerza de trabajo: el producto pertenece al capitalista, la actividad es forzada, y el trabajador se distancia de su esencia humana y de los demás hombres.",
          "medium"),
        q("¿En qué se diferencian fundamentalmente los contratos sociales de Hobbes y Rousseau?",
          "Hobbes establece un contrato que cede todo el poder a un soberano absoluto e irrevocable; Rousseau propone que la soberanía reside en la voluntad general del pueblo y puede revocarse",
          "Hobbes y Rousseau coinciden en que el contrato social debe garantizar la monarquía absoluta",
          "Rousseau admite un soberano absoluto siempre que sea elegido democráticamente; Hobbes lo rechaza",
          "Ambos autores parten del mismo diagnóstico del estado de naturaleza como conflictivo y sin ley",
          "En Hobbes, los individuos ceden todos sus derechos a un Leviatán absoluto e irrevocable. En Rousseau, la soberanía nunca se transfiere: reside siempre en la voluntad general del pueblo, que puede revocar a quienes la traicionan.",
          "hard"),
    ],
    5: [
        q("¿Qué es el intelectualismo ético de Platón?",
          "La tesis de que nadie hace el mal voluntariamente: el mal proviene de la ignorancia, y quien conoce el bien necesariamente lo practica",
          "La idea de que la ética debe ser enseñada solo en las instituciones intelectuales y académicas",
          "La postura de que el conocimiento racional es incompatible con la vida moral virtuosa",
          "La teoría de que las acciones son buenas si producen placer intelectual en quien las realiza",
          "El intelectualismo ético de Platón sostiene que el bien es conocimiento: si alguien actúa mal es porque no conoce verdaderamente el bien. Por eso la educación filosófica es la vía para la virtud y la justicia.",
          "easy"),
        q("¿Qué es la eudaimonía en la ética aristotélica y cómo se alcanza?",
          "La felicidad o florecimiento humano, que se alcanza ejerciendo la virtud como término medio entre excesos y defectos",
          "Un estado de placer sensorial máximo que Aristóteles considera el fin último de la vida humana",
          "La inmortalidad del alma que se obtiene mediante la contemplación filosófica pura",
          "Un ideal abstracto imposible de alcanzar en la vida práctica, reservado solo para los dioses",
          "Para Aristóteles, la eudaimonía (felicidad, buen vivir) es el fin último de la acción humana y se alcanza ejerciendo las virtudes, entendidas como términos medios entre dos extremos viciosos.",
          "easy"),
        q("¿Qué es el imperativo categórico de Kant y por qué es 'categórico'?",
          "Es un mandato moral incondicional: 'actúa solo según aquella máxima que puedas querer que se convierta en ley universal'. Es categórico porque obliga independientemente de los deseos o consecuencias",
          "Es una recomendación moral que se aplica solo en ciertas situaciones dependiendo del contexto cultural",
          "Es un mandato hipotético: si quieres ser feliz, entonces actúa de determinada manera",
          "Es el principio que indica que la acción buena es la que produce la mayor felicidad para el mayor número",
          "Kant distingue imperativos hipotéticos (si quieres X, haz Y) de los categóricos (haz Y, sin condición). El imperativo categórico es la ley moral racional que obliga universalmente: una acción es moral si su máxima puede ser universalizada sin contradicción.",
          "medium"),
        q("¿Qué propone Levinas con su 'ética de la responsabilidad' frente al Otro?",
          "Que el rostro del Otro me interpela e impone una responsabilidad incondicional antes de cualquier elección o contrato",
          "Que la responsabilidad ética surge únicamente de acuerdos racionales entre sujetos autónomos e iguales",
          "Que el Otro es una amenaza que debe ser neutralizada antes de que pueda generar obligaciones morales",
          "Que la ética de la responsabilidad se limita a los vínculos familiares y no puede extenderse a extraños",
          "Para Levinas, el rostro del Otro (su vulnerabilidad y alteridad) me llama a una responsabilidad que no puedo eludir ni delegar. Esta relación ética con el Otro es anterior a cualquier sistema moral o contrato.",
          "medium"),
        q("¿Cuál es la diferencia fundamental entre la ética teleológica de Aristóteles y la ética deontológica de Kant?",
          "Aristóteles evalúa las acciones por su fin (el bien, la eudaimonía); Kant las evalúa por la intención y la universalidad de la máxima, independientemente de las consecuencias",
          "Aristóteles rechaza cualquier tipo de norma moral; Kant acepta normas pero solo si producen placer",
          "La ética kantiana evalúa consecuencias mientras que Aristóteles solo considera la intención del agente",
          "Ambas éticas coinciden en que la felicidad individual es el criterio último de moralidad",
          "La ética teleológica (telos: fin) de Aristóteles juzga las acciones según el fin que persiguen (la eudaimonía). La ética deontológica (deon: deber) de Kant juzga las acciones por el deber y la universalidad de la máxima, no por sus resultados.",
          "hard"),
    ],
    0: [
        q("¿Cuál es el vínculo entre la filosofía y el 'asombro' (thaumazein) según la tradición griega?",
          "El asombro ante lo desconocido es el origen y el motor de la filosofía: la capacidad de maravillarse impulsa la búsqueda racional",
          "El asombro es un obstáculo para la filosofía porque impide el pensamiento sistemático",
          "Solo la ciencia moderna reconoce el asombro como punto de partida del conocimiento",
          "El asombro es propio de la religión; la filosofía comienza con la duda metódica, no con el asombro",
          "Para Aristóteles y Platón, la filosofía nace del thaumazein (asombro, admiración). Ese estado de extrañamiento ante lo familiar es lo que impulsa al filósofo a preguntar y buscar fundamentos.",
          "medium"),
        q("¿En qué sentido la filosofía política moderna (Hobbes, Locke, Rousseau) rompe con Aristóteles?",
          "Los modernos conciben la sociedad como un artificio voluntario (contrato) y no como algo natural, cuestionando la idea aristotélica del hombre como animal político por naturaleza",
          "Los modernos recuperan íntegramente la teoría política aristotélica actualizando su vocabulario",
          "La ruptura consiste en que los modernos rechazan toda forma de gobierno y proponen el anarquismo",
          "Los modernos coinciden con Aristóteles en que la monarquía absoluta es la forma natural de gobierno",
          "Aristóteles veía la polis como algo natural al hombre. Los contractualistas modernos parten de individuos prepolíticos y construyen la sociedad mediante un acto voluntario de contrato, invirtiendo la relación naturaleza-política.",
          "hard"),
        q("¿Qué relación existe entre el concepto marxista de 'ideología' y la epistemología?",
          "Marx sostiene que las ideas dominantes de una época son las ideas de la clase dominante: el conocimiento no es neutro sino que refleja intereses de clase",
          "Para Marx, la ideología es un conocimiento puro y objetivo separado de las condiciones materiales",
          "La ideología marxista es equivalente al concepto de episteme griega: el conocimiento más riguroso",
          "Marx rechaza toda relación entre el conocimiento y las condiciones sociales de producción",
          "La crítica marxista de la ideología tiene implicancias epistemológicas: denuncia que lo que se presenta como conocimiento universal y neutro está condicionado por las relaciones de producción y sirve para legitimar el orden burgués.",
          "hard"),
        q("¿Cómo se relaciona la ética kantiana con la idea de dignidad humana?",
          "Para Kant, el ser humano siempre debe ser tratado como fin en sí mismo y nunca como mero medio, lo que funda su dignidad incondicional",
          "Kant considera que la dignidad humana depende del mérito individual y puede perderse por malas acciones",
          "La dignidad en Kant es relativa al contrato social y varía según la cultura y la época",
          "Kant vincula la dignidad únicamente a los seres con capacidad de sentir placer y dolor",
          "El imperativo categórico tiene una formulación práctica: 'actúa de tal modo que trates a la humanidad, en tu persona y en la de cualquier otro, siempre como fin y nunca solo como medio'. Esta fórmula funda la dignidad humana universal.",
          "medium"),
        q("¿Qué aporta la Filosofía de la Liberación latinoamericana a la ética comunicativa de Habermas?",
          "Critica que la ética comunicativa ignora las asimetrías de poder y las condiciones de exclusión de los pueblos periféricos, que no participan en igualdad en el diálogo",
          "La Filosofía de la Liberación acepta íntegramente la ética comunicativa sin ninguna objeción",
          "Enrique Dussel coincide con Habermas en que todos los participantes del diálogo tienen igual capacidad de argumentación",
          "La crítica latinoamericana rechaza la ética en general por considerarla un instrumento de dominación cultural",
          "Enrique Dussel y la Filosofía de la Liberación señalan que la ética comunicativa presupone un diálogo entre iguales que no existe en la realidad: los excluidos y los pueblos del Sur Global no tienen voz real en el consenso que Habermas idealiza.",
          "hard"),
        q("¿Cómo desafía el existencialismo la noción tradicional de 'naturaleza humana'?",
          "El existencialismo niega que haya una naturaleza humana fija y universal: el ser humano es lo que se hace a sí mismo mediante sus elecciones",
          "El existencialismo recupera la idea aristotélica de que el hombre tiene una esencia natural determinada",
          "Para el existencialismo, la naturaleza humana está completamente determinada por factores biológicos",
          "El existencialismo acepta la naturaleza humana cristiana (alma inmortal) y la reformula en términos seculares",
          "El existencialismo (Sartre, Heidegger, Beauvoir) rechaza cualquier esencia humana predefinida. La libertad radical implica que cada individuo construye su ser a través de sus decisiones, cargando con la angustia de no tener una naturaleza que lo guíe.",
          "hard"),
        q("¿Qué tienen en común la epistemología, la antropología y la ética como ramas de la filosofía?",
          "Las tres preguntan por el ser humano: la epistemología por su capacidad de conocer, la antropología por su naturaleza, y la ética por cómo debe actuar",
          "Las tres ramas son independientes y no comparten ningún problema filosófico fundamental",
          "El hilo conductor es el estudio de la naturaleza física y biológica del ser humano",
          "Solo la ética y la epistemología están relacionadas; la antropología pertenece a las ciencias sociales",
          "La filosofía reflexiona sobre el ser humano desde distintos ángulos: su conocimiento (epistemología), su naturaleza (antropología) y su acción (ética). En todos los casos, el sujeto humano y su situación en el mundo son el punto de referencia central.",
          "hard"),
        q("¿Qué es el 'estado de naturaleza' y por qué es clave en la filosofía política moderna?",
          "Es una hipótesis teórica sobre cómo sería la vida humana sin instituciones políticas; sirve para justificar o cuestionar el origen y la legitimidad del Estado",
          "Es un período histórico documentado que los filósofos modernos estudiaron mediante la arqueología",
          "Es la condición de armonía perfecta en la que vivían los hombres antes de la aparición del lenguaje",
          "Refiere al ecosistema natural que los hombres debían dominar para fundar la civilización",
          "El estado de naturaleza es un experimento mental (no un período histórico real) que los contractualistas usan para deducir por qué los hombres formarían una sociedad y bajo qué condiciones el Estado es legítimo.",
          "medium"),
        q("¿Qué es la 'voluntad general' de Rousseau y cómo se distingue de la 'voluntad de todos'?",
          "La voluntad general busca el bien común de la comunidad; la voluntad de todos es la suma de intereses particulares, que pueden no coincidir con el bien común",
          "La voluntad general y la voluntad de todos son sinónimos: ambas refieren a la decisión de la mayoría",
          "La voluntad general es la del soberano absoluto; la voluntad de todos es la de los ciudadanos sin poder político",
          "Rousseau rechaza tanto la voluntad general como la voluntad de todos, prefiriendo la voluntad del filósofo-rey",
          "La volonté de tous suma voluntades particulares con intereses egoístas. La volonté générale trasciende esos intereses y apunta al bien común; es inalienable, indivisible y siempre recta aunque puede estar equivocada sobre los medios.",
          "hard"),
        q("Según el módulo de Antropología Filosófica, ¿qué reveló el mito de Edipo sobre el autoconocimiento?",
          "Que el autoconocimiento es un proceso doloroso y difícil: Edipo creía conocerse pero al final descubrió una verdad devastadora sobre su propio origen",
          "Que el autoconocimiento es fácil y accesible para cualquier persona que reflexione brevemente",
          "Que el mito de Edipo prueba que el destino del hombre está completamente determinado y el conocimiento es inútil",
          "Que Edipo alcanzó el autoconocimiento gracias a la razón filosófica y no al sufrimiento personal",
          "El módulo usa el mito de Edipo para ilustrar la complejidad del autoconocimiento: Edipo creía saber quién era pero ignoraba su verdad más profunda. Solo a través del sufrimiento llegó a conocerse, cumpliéndose la consigna délfica.",
          "medium"),
        q("¿Cómo articula la filosofía contemporánea el problema del 'Otro' con la política de la identidad?",
          "La alteridad (el Otro como diferente) cuestiona los sistemas éticos y políticos basados en la identidad homogénea y exige reconocer la diversidad de género, cultura e identidades emergentes",
          "La filosofía contemporánea ignora el problema del Otro y se concentra solo en el sujeto individual",
          "El problema del Otro concluye que todas las identidades son idénticas en el fondo",
          "Solo la filosofía analítica aborda el problema del Otro; la continental lo considera irrelevante",
          "A partir de Levinas, la filosofía contemporánea problematiza la relación con el Otro como diferente. Esto se expande en debates sobre el género, las identidades culturales y los pueblos excluidos, cuestionando los universalismos abstractos que invisibilizan la diferencia.",
          "hard"),
        q("¿Qué comparten la ironía socrática y la hermenéutica como modos de acceso al conocimiento?",
          "Ambas parten de que el conocimiento no es una posesión inmediata sino que requiere un proceso de cuestionamiento e interpretación que transforma al sujeto",
          "Ambas sostienen que el conocimiento es imposible y que la filosofía debe limitarse a describir la ignorancia",
          "La ironía socrática y la hermenéutica son métodos opuestos: una niega el saber, la otra lo afirma",
          "Ambas son métodos exclusivamente científicos sin relevancia para la filosofía práctica",
          "La ironía socrática revela que saber no es tener respuestas sino saber preguntar. La hermenéutica muestra que comprender es un proceso circular y activo. Ambas coinciden en que el conocimiento no es una captación directa sino una práctica transformadora.",
          "hard"),
        q("¿Cómo conectan el intelectualismo ético de Platón y el imperativo categórico de Kant?",
          "Ambos fundan la moralidad en la razón: Platón en el conocimiento del bien, Kant en la ley racional universal",
          "Platón y Kant coinciden en que la ética depende de las consecuencias felices de las acciones",
          "Ambos rechazan que la razón pueda fundamentar la moral y recurren a la intuición emocional",
          "Son posiciones opuestas: Platón funda la ética en el conocimiento, Kant en la experiencia sensible",
          "Platón sostiene que el bien se conoce racionalmente y que nadie yerra voluntariamente. Kant sostiene que la ley moral es racional y universalizable. Ambos comparten que la razón (no las emociones ni las consecuencias) funda la moralidad.",
          "hard"),
        q("¿Qué tienen en común Nietzsche y Marx en su crítica a la moral y la ideología dominante?",
          "Ambos denuncian que los valores morales dominantes no son universales ni neutrales sino instrumentos que sirven a intereses de poder o de clase",
          "Ambos proponen volver a los valores griegos clásicos como alternativa a la moral moderna",
          "Marx y Nietzsche defienden el mismo tipo de sociedad ideal: uno el comunismo, el otro también",
          "Ambos aceptan la moral kantiana pero critican su aplicación en las sociedades capitalistas",
          "Nietzsche denuncia que la moral cristiana es una 'moral de esclavos' que sirve al resentimiento. Marx denuncia que la ideología moral dominante sirve a los intereses de la clase dominante. Ambos muestran que la 'moral universal' esconde relaciones de poder.",
          "hard"),
        q("¿Por qué la filosofía no puede ser reemplazada por las ciencias particulares?",
          "Porque las ciencias estudian regiones específicas de lo real, mientras que la filosofía reflexiona sobre los fundamentos, el sentido y los límites del conocimiento en general",
          "Porque la filosofía es más antigua que las ciencias y por eso tiene mayor autoridad epistémica",
          "Porque las ciencias particulares han demostrado ser incapaces de producir conocimiento verdadero",
          "Porque la filosofía estudia los mismos objetos que las ciencias pero con mayor rigor experimental",
          "Las ciencias particulares delimitan su objeto (física, biología, sociología) y no pueden preguntarse por sus propios fundamentos ni por el conocimiento en general. La filosofía ocupa ese espacio reflexivo: pregunta por qué y cómo es posible el conocimiento, qué es la realidad, qué debemos hacer.",
          "medium"),
    ],
}
