def q(question, correct, wrong1, wrong2, wrong3, explanation, difficulty="medium"):
    return {
        "question": question,
        "options": [
            {"text": correct, "is_correct": True},
            {"text": wrong1,  "is_correct": False},
            {"text": wrong2,  "is_correct": False},
            {"text": wrong3,  "is_correct": False},
        ],
        "explanation": explanation,
        "difficulty":  difficulty,
    }

QUESTIONS = {
    # ── Módulo 1: Lógica ─────────────────────────────────────────────────────
    1: [
        q("¿Qué es una proposición en lógica?",
          "Una oración declarativa con sentido de la cual se puede inferir si es verdadera o falsa",
          "Cualquier oración que contenga un verbo",
          "Una expresión matemática sin valor de verdad",
          "Una pregunta que admite respuesta sí/no",
          "Una proposición es una oración declarativa con sentido de la cual se puede inferir si es verdadera o falsa. Se simbolizan con letras minúsculas y pueden ser simples o compuestas.",
          "easy"),

        q("¿Cuándo es FALSA la implicación p ⇒ q?",
          "Solo cuando el antecedente p es verdadero y el consecuente q es falso",
          "Solo cuando ambas proposiciones son falsas",
          "Cuando p es falso y q es verdadero",
          "Cuando ambas proposiciones son verdaderas",
          "La implicación p ⇒ q solo es FALSA si el antecedente es verdadero y el consecuente falso. En todos los demás casos (incluyendo antecedente falso) la implicación es verdadera.",
          "easy"),

        q("¿Cuándo es VERDADERA la conjunción p ∧ q?",
          "Solo cuando ambas proposiciones p y q son verdaderas",
          "Cuando al menos una de las proposiciones es verdadera",
          "Cuando ambas proposiciones son falsas",
          "Cuando p es verdadera y q es falsa",
          "La conjunción p ∧ q (p y q) es VERDADERA únicamente si las dos proposiciones son verdaderas. En cualquier otro caso es FALSA.",
          "medium"),

        q("¿Qué representa el conectivo lógico ⇔ (doble implicación)?",
          "Es verdadera solo si ambas proposiciones tienen el mismo valor de verdad (ambas V o ambas F)",
          "Es verdadera cuando p implica a q pero no al revés",
          "Es verdadera cuando al menos una de las dos proposiciones es verdadera",
          "Es siempre falsa cuando una proposición es verdadera y la otra falsa",
          "La doble implicación p ⇔ q (p si y solo si q) es VERDADERA cuando ambas proposiciones son verdaderas o ambas son falsas, es decir, cuando tienen el mismo valor de verdad.",
          "medium"),

        q("¿Cuál es la relación entre la implicación directa p ⇒ q y su contrarrecíproca?",
          "La contrarrecíproca es ¬q ⇒ ¬p, y es lógicamente equivalente a la implicación directa",
          "La contrarrecíproca es q ⇒ p, y es equivalente a la recíproca",
          "La contrarrecíproca es ¬p ⇒ ¬q, llamada también implicación contraria",
          "La contrarrecíproca es siempre falsa cuando la directa es verdadera",
          "Dada p ⇒ q: la recíproca es q ⇒ p, la contraria es ¬p ⇒ ¬q, y la contrarrecíproca es ¬q ⇒ ¬p. La contrarrecíproca es lógicamente equivalente a la implicación directa.",
          "hard"),
    ],

    # ── Módulo 2: Teoría de conjuntos ────────────────────────────────────────
    2: [
        q("¿Cómo se define un conjunto por extensión?",
          "Enumerando todos sus elementos entre llaves, por ejemplo A = {a, e, i, o, u}",
          "Describiendo la propiedad o característica común que reúnen sus elementos",
          "Indicando que el conjunto no tiene elementos (conjunto vacío)",
          "Usando el conjunto universal U como referencia",
          "Un conjunto por extensión se define enumerando explícitamente todos sus elementos. Por ejemplo A = {a, e, i, o, u}. En cambio, por comprensión se describe la característica: A = {x / x son las vocales}.",
          "easy"),

        q("¿Qué es el conjunto vacío?",
          "El conjunto que no tiene ningún elemento, simbolizado con ∅",
          "El conjunto que tiene un único elemento",
          "El conjunto universal que contiene todos los elementos posibles",
          "El conjunto cuyos elementos son indefinidos",
          "El conjunto vacío es aquel que carece de elementos. Se simboliza con ∅ (o también con {}). No debe confundirse con el conjunto unitario, que tiene exactamente un elemento.",
          "easy"),

        q("¿Qué representa la intersección A ∩ B?",
          "El conjunto formado por los elementos que pertenecen a A y a B al mismo tiempo",
          "El conjunto formado por los elementos que pertenecen a A o a B",
          "Los elementos de A que no pertenecen a B",
          "Todos los elementos del conjunto universal U",
          "La intersección A ∩ B es el conjunto de elementos comunes a ambos conjuntos; deben pertenecer a A y a B simultáneamente. No debe confundirse con la unión (A ∪ B) que incluye los elementos de uno u otro.",
          "medium"),

        q("¿Qué significa que A ⊂ B (A incluido en B)?",
          "Que todos y cada uno de los elementos de A pertenecen también al conjunto B",
          "Que A y B tienen exactamente los mismos elementos",
          "Que A tiene más elementos que B",
          "Que la intersección de A y B es el conjunto vacío",
          "La inclusión A ⊂ B (A está incluido en B) significa que todo elemento de A es también elemento de B. Si además B tiene elementos que no están en A, la inclusión es propia.",
          "medium"),

        q("¿Qué es el complemento de A (Aᶜ) respecto del conjunto universal U?",
          "El conjunto formado por todos los elementos de U que NO pertenecen a A",
          "El conjunto formado por los elementos comunes entre A y U",
          "La unión de A con el conjunto vacío",
          "Los elementos de A que tampoco pertenecen a ningún otro conjunto",
          "El complemento de A respecto de U es Aᶜ = U - A, es decir, todos los elementos del universal que no están en A. Es la diferencia U - A.",
          "hard"),
    ],

    # ── Módulo 3: Funciones ──────────────────────────────────────────────────
    3: [
        q("¿Cuál es la condición que define a una función?",
          "A cada elemento del dominio le corresponde un único elemento del codominio",
          "A cada elemento del dominio pueden corresponderle varios valores del codominio",
          "El dominio y el codominio deben ser conjuntos iguales",
          "La función debe ser siempre creciente",
          "Una función es una relación donde a cada elemento x del dominio le corresponde un único valor y del codominio. Si a un mismo x le correspondieran dos valores distintos, no sería función.",
          "easy"),

        q("En f(x) = y, ¿qué son el dominio y el codominio?",
          "El dominio es el conjunto de valores de x (variable independiente) y el codominio es el de y (variable dependiente)",
          "El dominio son los valores de y y el codominio los de x",
          "Ambos representan los posibles valores de y",
          "Son los nombres de los ejes cartesianos horizontal y vertical",
          "En una función, x es la variable independiente y su conjunto de valores es el dominio. La variable dependiente y (o f(x)) toma sus valores en el codominio.",
          "easy"),

        q("¿Cuál es la diferencia entre funciones algebraicas y trascendentes?",
          "Las algebraicas solo usan operaciones racionales y radicación; las trascendentes incluyen funciones como logaritmos, exponenciales y trigonométricas",
          "Las algebraicas incluyen funciones trigonométricas; las trascendentes solo usan suma y resta",
          "Las trascendentes no tienen dominio definido",
          "Son equivalentes: cualquier función algebraica puede escribirse como trascendente",
          "Las funciones algebraicas se obtienen con operaciones racionales (+, -, ×, ÷) y radicación. Las trascendentes tienen la variable afectada por otras funciones: logarítmicas, exponenciales (2ˣ), trigonométricas (sen, cos).",
          "medium"),

        q("En una función lineal f(x) = mx + b, ¿qué indica que m > 0?",
          "La recta es creciente: sube de izquierda a derecha en el plano cartesiano",
          "La recta es decreciente: baja de izquierda a derecha",
          "La recta es horizontal (constante)",
          "La función no tiene representación gráfica válida",
          "En f(x) = mx + b, m es la pendiente. Si m > 0 la recta es creciente; si m = 0 es constante (horizontal); si m < 0 es decreciente.",
          "medium"),

        q("¿Cuál es la diferencia entre funciones racionales enteras y fraccionarias?",
          "Las enteras son monomios o polinomios (sin cociente); las fraccionarias son cocientes de monomios y polinomios",
          "Las enteras incluyen radicales; las fraccionarias no",
          "Las fraccionarias no admiten variables en el denominador",
          "Son sinónimos dentro del álgebra elemental",
          "Dentro de las funciones racionales: las enteras (o polinomiales) no tienen la variable en el denominador (monomios, polinomios); las fraccionarias sí: son cocientes de monomios y polinomios.",
          "hard"),
    ],

    # ── Módulo 4: Análisis combinatorio ──────────────────────────────────────
    4: [
        q("¿Qué es el factorial de n (n!)?",
          "El producto de n por todos los enteros positivos menores hasta 1: n.(n-1).(n-2)…2.1",
          "La suma de todos los números naturales de 1 a n",
          "El cociente de n entre n-1",
          "El número de combinaciones de n elementos tomados de a 2",
          "n! = n.(n-1).(n-2)…3.2.1. Por definición, 0! = 1. Por ejemplo: 4! = 4×3×2×1 = 24.",
          "easy"),

        q("¿Cuándo dos variaciones se consideran distintas?",
          "Cuando difieren en sus elementos o en el orden en que aparecen",
          "Solo cuando todos sus elementos son diferentes",
          "Solo cuando tienen distinta longitud",
          "Cuando tienen los mismos elementos pero en diferente cantidad",
          "Las variaciones consideran tanto los elementos como su orden. Dos variaciones son distintas si difieren en algún elemento o si los mismos elementos aparecen en diferente orden.",
          "easy"),

        q("¿Cuál es la diferencia principal entre permutaciones y combinaciones?",
          "En las permutaciones importa el orden de los elementos; en las combinaciones no importa el orden",
          "Las permutaciones usan todos los m elementos; las combinaciones pueden usar todos o algunos",
          "Las combinaciones permiten repetición de elementos; las permutaciones no",
          "No hay diferencia práctica: ambas dan el mismo resultado",
          "La diferencia clave: en permutaciones el ORDEN importa (AB ≠ BA); en combinaciones el orden no importa (AB = BA). Esto se refleja en que Cₘʳ = Vₘʳ / r!.",
          "medium"),

        q("Si m = 6 y r = 3, ¿cuántas variaciones Vₘʳ existen?",
          "120, porque V₆³ = 6!/(6-3)! = 6×5×4 = 120",
          "20",
          "36",
          "720",
          "V₆³ = 6!/(6-3)! = 6!/3! = (6×5×4×3×2×1)/(3×2×1) = 720/6 = 120. Se calculan los r primeros factores descendientes desde m.",
          "medium"),

        q("¿Por qué la fórmula de combinaciones Cₘʳ = Vₘʳ / r! divide por r! (las permutaciones de r)?",
          "Porque en las combinaciones el orden no importa: un mismo grupo contado en r! órdenes distintos cuenta como uno solo",
          "Para obtener un resultado fraccionario que represente porcentajes",
          "Porque r! representa los elementos del conjunto que NO fueron seleccionados",
          "Para que el resultado sea siempre mayor que las variaciones correspondientes",
          "Dado un grupo de r elementos, existen r! formas de ordenarlos (permutaciones). Como en combinaciones todos esos ordenamientos son el mismo grupo, se divide Vₘʳ por r! para eliminar los conteos duplicados.",
          "hard"),
    ],

    # ── Módulo 5: Probabilidades ──────────────────────────────────────────────
    5: [
        q("¿Cómo se calcula la probabilidad de un suceso S?",
          "P(S) = número de casos favorables / número de casos totales posibles",
          "P(S) = número de casos totales / número de casos favorables",
          "P(S) = casos favorables − casos desfavorables",
          "P(S) = raíz cuadrada de los casos favorables",
          "La probabilidad clásica se define como P(S) = casos favorables / casos totales, siempre que todos los casos sean igualmente posibles.",
          "easy"),

        q("¿Entre qué valores puede estar la probabilidad de cualquier suceso?",
          "Entre 0 y 1 inclusive: 0 ≤ P(A) ≤ 1",
          "Entre −1 y 1",
          "Entre 0 y 100",
          "Entre 0.5 y 1",
          "La probabilidad siempre está acotada entre 0 (suceso imposible) y 1 (suceso seguro). Un valor de 0 indica que el suceso nunca ocurre; un valor de 1 indica que siempre ocurre.",
          "easy"),

        q("¿Cuándo dos sucesos son complementarios o contrarios?",
          "Cuando siempre ocurre exactamente uno de los dos, y sus probabilidades suman 1: P(A) + P(B) = 1",
          "Cuando ambos sucesos pueden ocurrir simultáneamente",
          "Cuando tienen exactamente la misma probabilidad",
          "Cuando uno de ellos tiene probabilidad 0",
          "Dos sucesos son complementarios si presentan siempre uno y solo uno. Sus probabilidades suman 1: P(A) + P(Aᶜ) = 1, por lo que P(A) = 1 − P(Aᶜ).",
          "medium"),

        q("¿Cuándo se aplica el principio de probabilidades totales P(A o B) = P(A) + P(B)?",
          "Cuando A y B son sucesos incompatibles: no pueden ocurrir simultáneamente",
          "Siempre que se quieran sumar dos probabilidades",
          "Solo cuando P(A) = P(B)",
          "Cuando A y B pueden ocurrir al mismo tiempo",
          "El principio de probabilidades totales P(A o B) = P(A) + P(B) solo aplica cuando los sucesos son INCOMPATIBLES (mutuamente excluyentes). Si pudieran ocurrir juntos, se restaría la intersección.",
          "medium"),

        q("Si P(A) = 0.3 y P(B) = 0.5, y A y B son incompatibles, ¿cuál es P(A o B)?",
          "0.8, porque P(A o B) = P(A) + P(B) = 0.3 + 0.5 = 0.8",
          "0.15, porque se multiplican las probabilidades",
          "0.2, porque se restan",
          "No se puede calcular sin saber el número de casos totales",
          "Como A y B son incompatibles, P(A o B) = P(A) + P(B) = 0.3 + 0.5 = 0.8. Si no fueran incompatibles habría que restar P(A ∩ B).",
          "hard"),
    ],

    # ── Módulo 6: Estadística ─────────────────────────────────────────────────
    6: [
        q("¿Cuál es la diferencia entre estadística descriptiva y estadística inferencial?",
          "La descriptiva organiza y describe los datos de la muestra; la inferencial extrae conclusiones para la población total",
          "La descriptiva analiza poblaciones enteras; la inferencial analiza solo muestras pequeñas",
          "Son sinónimos: ambas hacen lo mismo con distintos nombres",
          "La inferencial solo trabaja con variables cualitativas",
          "La estadística descriptiva describe, visualiza y organiza los datos observados. La estadística inferencial usa esos datos para hacer inferencias y predicciones sobre el universo o población total.",
          "easy"),

        q("¿Cuál es la diferencia entre variables cuantitativas discretas y continuas?",
          "Las discretas solo toman valores naturales (nº de hermanos); las continuas pueden tomar cualquier valor real en un intervalo (peso, tiempo)",
          "Las discretas son siempre números más grandes que las continuas",
          "Las continuas solo toman valores enteros positivos",
          "Las discretas incluyen decimales; las continuas solo admiten enteros",
          "Las variables discretas tienen recorrido finito o contable (nº de hermanos: 0,1,2…). Las continuas pueden tomar cualquier valor real dentro de un intervalo (ej. el peso puede ser 65.3 kg).",
          "easy"),

        q("¿Qué mide la mediana de un conjunto de datos?",
          "El valor central que divide los datos ordenados en dos mitades iguales: 50% por encima y 50% por debajo",
          "El valor que aparece con mayor frecuencia en el conjunto",
          "La suma de todos los valores dividida por la cantidad de datos",
          "El promedio entre el valor máximo y el mínimo",
          "La mediana es el valor que ocupa el lugar central cuando los datos están ordenados. Exactamente el 50% de los datos queda por debajo y el 50% por encima. No debe confundirse con la media (promedio) ni con la moda.",
          "medium"),

        q("¿Qué mide la moda en estadística?",
          "El valor o valores que aparecen con mayor frecuencia en el conjunto de datos",
          "El valor que divide al conjunto en dos mitades iguales",
          "El promedio aritmético de todos los datos",
          "La diferencia entre el valor máximo y el valor mínimo del conjunto",
          "La moda es el valor más frecuente (el que más se repite). Un conjunto puede tener una moda (unimodal), dos (bimodal) o más. Si todos los valores se repiten igual cantidad de veces, no hay moda.",
          "medium"),

        q("¿Qué ventaja tiene la mediana sobre la media aritmética para representar un conjunto de datos?",
          "La mediana no se distorsiona por valores extremos (outliers), mientras que la media puede ser muy afectada por datos muy altos o muy bajos",
          "La mediana siempre es mayor que la media aritmética",
          "La mediana considera todos los valores con igual peso, igual que la media",
          "La mediana es más fácil de calcular en todos los casos que la media",
          "La media aritmética suma todos los valores, por lo que un outlier extremo la desplaza significativamente. La mediana, al ser el valor central en los datos ordenados, no cambia ante la presencia de valores atípicos.",
          "hard"),
    ],

    # ── Generales ─────────────────────────────────────────────────────────────
    0: [
        q("¿Cómo se relaciona la teoría de conjuntos con el cálculo de probabilidades?",
          "Las operaciones entre conjuntos (unión, intersección, complemento) se usan directamente para calcular probabilidades de sucesos combinados",
          "No tienen ninguna relación: son ramas completamente independientes",
          "Los conjuntos solo se aplican en álgebra, no en probabilidades",
          "La probabilidad reemplaza a la teoría de conjuntos en problemas avanzados",
          "El espacio muestral de un experimento es un conjunto; los sucesos son subconjuntos. La unión corresponde a 'A o B', la intersección a 'A y B' y el complemento a 'no A'. Las operaciones de conjuntos son el lenguaje natural de la probabilidad.",
          "medium"),

        q("¿En qué situación se aplica el análisis combinatorio para calcular probabilidades?",
          "Cuando se necesita contar el número de casos favorables y totales en problemas donde la selección o el orden de elementos importa",
          "Solo cuando los eventos son totalmente independientes",
          "El análisis combinatorio no tiene aplicación en el cálculo de probabilidades",
          "Solo cuando hay exactamente dos eventos posibles",
          "Para calcular P(S) = casos favorables / casos totales, muchas veces es necesario CONTAR esos casos. El análisis combinatorio (variaciones, permutaciones, combinaciones) provee las herramientas para ese conteo.",
          "medium"),

        q("¿Qué diferencia hay entre una muestra y el universo en estadística?",
          "El universo es el conjunto completo de todas las unidades experimentales; la muestra es un subconjunto representativo del universo",
          "La muestra siempre es más grande que el universo",
          "Son equivalentes: el universo y la muestra contienen los mismos datos",
          "El universo es la muestra cuando se trabaja con datos del pasado",
          "El universo (o población) incluye a todos los entes que se quieren estudiar. La muestra es solo una parte de ese universo, elegida para representarlo y facilitar el estudio estadístico.",
          "easy"),

        q("Si una función lineal tiene pendiente m = 0, ¿qué tipo de recta representa?",
          "Una recta horizontal (función constante), ya que f(x) = b para todo valor de x",
          "Una recta vertical, ya que no crece ni decrece",
          "Una parábola de vértice en el origen",
          "Una función sin gráfica válida porque la pendiente es nula",
          "En f(x) = mx + b, si m = 0 entonces f(x) = b (constante). Su gráfica es una recta horizontal. Las rectas verticales no representan funciones porque a un x le corresponderían infinitos valores.",
          "easy"),

        q("¿Qué tienen en común las variaciones y las combinaciones como herramientas del análisis combinatorio?",
          "Ambas cuentan grupos de r elementos tomados de un conjunto de m, pero las variaciones consideran el orden y las combinaciones no",
          "Ambas dan siempre el mismo resultado numérico",
          "Ambas ignoran el orden de los elementos",
          "Ambas requieren que r sea mayor que m",
          "Vmʳ cuenta grupos donde el orden importa (AB ≠ BA). Cmʳ cuenta grupos donde el orden no importa (AB = BA). La relación es Cmʳ = Vmʳ / r!, ya que cada grupo de combinaciones se cuenta r! veces en las variaciones.",
          "medium"),

        q("¿Qué relación hay entre el complemento de un conjunto A y el complemento de un suceso en probabilidades?",
          "En ambos casos el complemento contiene todo lo que NO pertenece a A; en conjuntos Aᶜ = U − A; en probabilidades P(Aᶜ) = 1 − P(A)",
          "Son conceptos sin relación: el complemento de conjuntos no aplica en probabilidades",
          "En probabilidades el complemento siempre tiene probabilidad 0",
          "En conjuntos el complemento de A es siempre el vacío",
          "La analogía es directa: el conjunto Aᶜ contiene los elementos que no están en A (respecto de U). En probabilidades, el suceso complementario Aᶜ incluye todos los resultados que no son A, y P(Aᶜ) = 1 − P(A).",
          "hard"),

        q("¿Qué limitación tiene la estadística descriptiva frente a la inferencial?",
          "La descriptiva solo resume los datos observados en la muestra, sin generalizaciones; la inferencial permite hacer predicciones sobre la población total",
          "La estadística descriptiva es más precisa que la inferencial en todos los casos",
          "La inferencial no utiliza datos reales; trabaja solo con simulaciones",
          "La descriptiva trabaja con poblaciones más grandes que la inferencial",
          "La estadística descriptiva organiza, visualiza y resume lo que se observó. No va más allá de los datos disponibles. La inferencial, en cambio, usa esos datos para inferir propiedades del universo completo.",
          "medium"),

        q("¿Cómo distinguir una variable cualitativa de una cuantitativa en un estudio estadístico?",
          "Las cualitativas no se pueden medir numéricamente (sexo, nacionalidad); las cuantitativas tienen un valor numérico (edad, precio, ingresos)",
          "Las cualitativas siempre representan cantidades; las cuantitativas representan categorías",
          "Las cuantitativas son siempre variables discretas; las cualitativas son continuas",
          "No hay diferencia práctica: ambas se analizan con la misma fórmula",
          "Las variables cualitativas expresan categorías o atributos no medibles numéricamente (sexo, color, nacionalidad). Las cuantitativas tienen un valor numérico que permite operar con ellas (edad, peso, precio).",
          "easy"),

        q("¿En qué se diferencia una proposición lógica de una variable estadística?",
          "Una proposición toma valores de verdad (V o F); una variable estadística toma valores numéricos o cualitativos que se distribuyen en una población",
          "Son conceptos equivalentes: ambos describen características de objetos",
          "Las variables estadísticas solo pueden tomar dos valores, igual que las proposiciones",
          "Las proposiciones son siempre cuantitativas; las variables estadísticas son cualitativas",
          "Una proposición es una oración declarativa con valor V o F. Una variable estadística es cualquier característica observable de las unidades de estudio y puede tomar muchos valores distintos, no solo dos.",
          "hard"),

        q("¿Por qué la implicación p ⇒ q es verdadera cuando p es falso, independientemente de q?",
          "Porque una premisa falsa no puede invalidar la conclusión: si el punto de partida no se cumple, la implicación no se viola",
          "Porque cualquier proposición falsa hace que todo sea verdadero",
          "Porque en lógica, lo falso y lo verdadero son equivalentes",
          "Porque la implicación siempre es verdadera, sea cual sea el valor de sus componentes",
          "La implicación p ⇒ q solo se 'rompe' cuando afirmamos p (premisa verdadera) pero q no se cumple. Si p es falso, nunca activamos la promesa, por lo que no hay incumplimiento. Esto se llama verdad vacua.",
          "hard"),
    ],
}
