"""
Quizzes de Seminario de Ingreso 2026.
Módulos: 1, 2, 3, 4, 6, 7, 8 (el PDF no tiene Módulo 5).
5 preguntas por módulo + 10 generales = 45 preguntas.
"""

def q(question, correct, wrong1, wrong2, wrong3, explanation, difficulty="medium"):
    return {
        "question": question,
        "options": [
            {"text": correct,  "is_correct": True},
            {"text": wrong1,   "is_correct": False},
            {"text": wrong2,   "is_correct": False},
            {"text": wrong3,   "is_correct": False},
        ],
        "explanation": explanation,
        "difficulty":  difficulty,
    }


QUESTIONS = {

    # ── Módulo 1: Introducción ─────────────────────────────────────────────────
    1: [
        q("¿Cuál es el propósito principal del Módulo 1 de Seminario?",
          "Presentar brevemente el programa y las formas de estudio del curso",
          "Desarrollar los conceptos de coherencia y cohesión textual",
          "Enseñar las normas de citación bibliográfica",
          "Explicar los géneros discursivos académicos",
          "El Módulo 1 es una introducción al programa y las formas de estudio; por eso no incluye contenido teórico.",
          "easy"),
        q("Según el Módulo 1, ¿qué característica distingue a este módulo del resto?",
          "No incluye contenido teórico",
          "Es el módulo más extenso del programa",
          "Está dedicado íntegramente a la escritura académica",
          "Presenta los géneros narrativos en detalle",
          "El Módulo 1 es explícito al decir que, por ser introductorio, no incluye contenido teórico.",
          "easy"),
        q("¿Qué implica estudiar en la universidad según la perspectiva de Seminario?",
          "Asumir una actitud crítica y sistemática, comprendiendo el texto con una metodología adecuada",
          "Memorizar la mayor cantidad de datos posibles antes de cada examen",
          "Transcribir fielmente los textos de las fuentes bibliográficas",
          "Aceptar sin cuestionamientos los postulados de los autores académicos",
          "El módulo plantea que estudiar es un trabajo que exige postura crítica y sistemática, comprender el texto y usar una metodología adecuada.",
          "medium"),
        q("¿Cuál de estas afirmaciones sobre el acto de estudiar es correcta según el programa de Seminario?",
          "Estudiar es pensar la práctica y exige humildad y actitud crítica",
          "Estudiar consiste en releer el material tantas veces como sea necesario",
          "Estudiar es un proceso pasivo donde el estudiante recibe información",
          "Estudiar no requiere relacionar los párrafos entre sí",
          "El programa sostiene que estudiar es una actitud frente al mundo que exige humildad y actitud crítica.",
          "medium"),
        q("¿Cuál de estas actividades describe mejor el enfoque del Seminario de Ingreso?",
          "Desarrollar habilidades de lectura comprensiva, interpretativa y crítica de textos académicos",
          "Aprender las reglas gramaticales del español normativo",
          "Practicar la oratoria y la expresión oral para exposiciones",
          "Estudiar historia de la literatura latinoamericana",
          "El Seminario se orienta a desarrollar habilidades de lectura y escritura académica en el nivel universitario.",
          "hard"),
    ],

    # ── Módulo 2: El Texto ─────────────────────────────────────────────────────
    2: [
        q("¿Qué es la coherencia global de un texto?",
          "La presencia de un tema central común a todas las partes del texto",
          "La relación gramatical entre las oraciones mediante pronombres y conectores",
          "El conjunto de paratextos que acompañan al texto",
          "La adecuación del texto al registro formal o informal",
          "La coherencia global refiere a que el texto tenga un tema central al que se subordinan todas sus partes.",
          "easy"),
        q("¿Cuál de los siguientes es un procedimiento de cohesión textual?",
          "La elipsis, que consiste en omitir una palabra o frase ya mencionada",
          "El paratexto icónico, que incluye imágenes visuales",
          "La coherencia local, que relaciona subtemas con el tema central",
          "El contexto histórico, que enmarca la producción del texto",
          "La elipsis es un mecanismo de cohesión que sustituye por cero elementos ya mencionados en el texto.",
          "easy"),
        q("¿Qué información aportan los paratextos antes de leer un texto?",
          "Permiten anticipar el contenido, el autor, el propósito y el contexto de publicación",
          "Reemplazan la lectura del texto principal cuando son suficientemente detallados",
          "Solo indican el formato gráfico del documento sin aportar contenido",
          "Son elementos decorativos sin función en la comprensión lectora",
          "Los paratextos permiten formular hipótesis de lectura sobre el origen, autor y propósito antes de leer el texto.",
          "medium"),
        q("¿Cuál es la diferencia entre coherencia local y coherencia global?",
          "La global refiere al tema central del texto entero; la local, a los subtemas que se relacionan con ese tema central",
          "La global se construye con conectores; la local, con pronombres de referencia",
          "La local depende del contexto histórico; la global, del contexto de situación",
          "La global aparece en textos largos; la local, solo en textos breves",
          "La coherencia global es el tema que unifica todo el texto; la local organiza los subtemas en relación con él.",
          "medium"),
        q("Un estudiante lee primero el título, el nombre del autor y la fuente de publicación antes de leer el cuerpo del texto. ¿Qué operación de lectura está realizando?",
          "Lectura de paratextos para construir hipótesis de lectura",
          "Lectura analítica para identificar la idea principal",
          "Poslectura para reconstruir el contenido mediante resumen",
          "Lectura global para realizar inferencias sobre el texto",
          "Leer primero los paratextos es el primer momento del proceso lector y permite anticipar y contextualizar el contenido.",
          "hard"),
    ],

    # ── Módulo 3: El Texto Segunda Parte ──────────────────────────────────────
    3: [
        q("¿Cuál es la diferencia entre texto y discurso según el Módulo 3?",
          "El texto es un conjunto de elementos lingüísticos organizados; el discurso es un uso específico de la lengua en un contexto situacional determinado",
          "El texto es siempre oral; el discurso, siempre escrito",
          "El texto incluye paratextos; el discurso, no",
          "El texto y el discurso son sinónimos perfectos sin ninguna diferencia",
          "El texto organiza elementos lingüísticos según reglas; el discurso agrega la dimensión del uso en un contexto situacional concreto.",
          "easy"),
        q("¿Qué es la adecuación como propiedad textual?",
          "La propiedad por la cual el texto se ajusta al contexto, los interlocutores, la finalidad comunicativa y el canal",
          "La ausencia de errores gramaticales y ortográficos en el texto",
          "La presencia de múltiples voces en el discurso del enunciador",
          "La repetición de términos clave para enfatizar la cohesión",
          "La adecuación implica que el texto responda al contexto discursivo, los interlocutores y la finalidad comunicativa.",
          "easy"),
        q("¿Qué caracteriza al registro especializado en el contexto universitario?",
          "Usa construcciones complejas y vocabulario técnico, y predomina en la comunicación escrita académica",
          "Emplea un vocabulario sencillo y accesible para el público en general",
          "Se utiliza exclusivamente en conversaciones orales informales entre pares",
          "Evita el uso de términos técnicos para facilitar la comprensión",
          "El registro especializado usa lenguaje técnico y construcciones complejas, y predomina en la escritura académica universitaria.",
          "medium"),
        q("¿Qué es el ethos académico?",
          "La imagen que un autor construye para presentarse como escritor académico reconocido por sus habilidades para organizar y producir textos válidos",
          "El conjunto de normas éticas que rigen la conducta de los investigadores",
          "El registro lingüístico formal utilizado exclusivamente en publicaciones científicas",
          "La comunidad de profesores que evalúan los trabajos de los estudiantes",
          "El ethos académico es la imagen discursiva que el autor construye para legitimarse como productor de conocimiento en la comunidad académica.",
          "medium"),
        q("¿En qué se diferencia la comunidad académica de la comunidad científica?",
          "La académica produce géneros pedagógicos como manuales y parciales; la científica produce géneros altamente especializados como artículos de investigación y tesis doctorales dirigidos a pares",
          "La académica incluye solo a docentes; la científica, solo a investigadores externos",
          "La académica usa registro informal; la científica, formal",
          "La académica se basa en la oralidad; la científica, en la escritura",
          "La comunidad académica se orienta a la enseñanza-aprendizaje con géneros pedagógicos; la científica produce conocimiento especializado para pares.",
          "hard"),
    ],

    # ── Módulo 4: Géneros Discursivos y Secuencias Textuales ──────────────────
    4: [
        q("¿Cuál de los siguientes es un rasgo EXTERNO de un género discursivo?",
          "La naturaleza del emisor, es decir, la formación de quien escribe",
          "El tema o asunto principal del texto",
          "El registro o estilo verbal utilizado",
          "La secuencia o estructura que define la intención del discurso",
          "Los rasgos externos son la naturaleza del emisor, la fuente de publicación y el destinatario. El tema, estilo y secuencia son rasgos internos.",
          "easy"),
        q("¿Qué secuencia textual corresponde a un texto que da instrucciones paso a paso para realizar una tarea?",
          "Secuencia instruccional",
          "Secuencia argumentativa",
          "Secuencia narrativa",
          "Secuencia dialogal",
          "La secuencia instruccional orienta hacia la ejecución de acciones según pasos que no pueden omitirse.",
          "easy"),
        q("¿Cuál es la función de la secuencia englobante o dominante en un texto?",
          "Definir la intención discursiva principal del texto, aunque el texto contenga otras secuencias subordinadas",
          "Eliminar las demás secuencias para que el texto sea homogéneo",
          "Establecer la coherencia local entre los párrafos del texto",
          "Indicar el registro lingüístico más adecuado para cada género",
          "La secuencia dominante define la intención discursiva del texto; las demás secuencias le quedan subordinadas.",
          "medium"),
        q("Un texto argumentativo busca convencer sobre una posición. ¿Qué tipo de argumento usa datos estadísticos o casos concretos como evidencia?",
          "Argumento empírico",
          "Argumento de autoridad",
          "Argumento de sentido común",
          "Argumento por analogía",
          "Los argumentos empíricos se basan en hechos concretos, datos estadísticos o casos verificables para fundamentar la hipótesis.",
          "medium"),
        q("¿Por qué se dice que la explicación y la argumentación forman un continuum en los géneros académicos?",
          "Porque ambas exponen razonadamente un tema, y en muchos textos académicos una puede convertirse en la otra según el enfoque del enunciador",
          "Porque la explicación siempre incluye un argumento de autoridad y la argumentación, una definición",
          "Porque los dos géneros utilizan exactamente las mismas secuencias textuales sin distinción",
          "Porque ambas requieren el uso obligatorio de conectores temporales",
          "Explicación y argumentación son polos de un continuum porque ambas exponen razones; la diferencia está en el grado de posicionamiento del enunciador.",
          "hard"),
    ],

    # ── Módulo 6: La Lectura ───────────────────────────────────────────────────
    6: [
        q("¿Qué implica 'leer las líneas' según Cassany (2006)?",
          "Comprender lo que el texto dice de manera explícita",
          "Identificar los paratextos que rodean al texto",
          "Cuestionar la ideología del autor y el destinatario del texto",
          "Reconstruir el contenido mediante resúmenes y esquemas",
          "'Leer las líneas' implica entender el contenido explícito del texto, a diferencia de 'leer entre líneas', que apunta a lo implícito.",
          "easy"),
        q("¿Cuál es el primer momento del proceso de lectura?",
          "La prelectura o lectura de los paratextos",
          "La lectura analítica por párrafos con subrayados",
          "La poslectura mediante resúmenes y mapas conceptuales",
          "La lectura global del texto completo",
          "El proceso lector comienza con la prelectura, donde se observan los paratextos y se formulan predicciones sobre el contenido.",
          "easy"),
        q("¿Qué caracteriza a la lectura crítica según el Módulo 6?",
          "Es contextualizada y cuestiona el contenido, el autor, el destinatario y la intencionalidad del texto",
          "Consiste en leer el texto varias veces hasta memorizar su contenido",
          "Se enfoca exclusivamente en detectar errores ortográficos y gramaticales",
          "Solo es posible si el lector tiene conocimientos previos del tema",
          "La lectura crítica, según Cassany, es contextualizada y cuestiona activamente el texto: su contenido, su autor y sus intenciones.",
          "medium"),
        q("¿Por qué el módulo recomienda que los estudiantes lean de manera 'crítica y rebelde'?",
          "Porque los textos académicos, aunque valiosos, no siempre son acertados y pueden ser superados por nuevas ideas",
          "Porque los profesores esperan que los estudiantes contradigan siempre las fuentes bibliográficas",
          "Porque los textos universitarios carecen de rigor científico y deben cuestionarse",
          "Porque la lectura rebelde garantiza mejores calificaciones en los exámenes",
          "El módulo señala que aunque los textos universitarios tienen valor académico, no son infalibles, por lo que la lectura debe ser crítica sin sumisión al autor.",
          "medium"),
        q("¿Por qué es importante conocer el género discursivo al que pertenece un texto antes de leerlo?",
          "Porque cada género tiene características propias que facilitan su comprensión e interpretación crítica",
          "Porque el género determina si el texto tiene paratextos o no",
          "Porque solo los géneros académicos requieren lectura comprensiva",
          "Porque el género indica automáticamente la posición ideológica del autor",
          "Conocer el género permite anticipar su estructura, propósito y registro, lo que facilita la comprensión y la lectura crítica.",
          "hard"),
    ],

    # ── Módulo 7: La Escritura ─────────────────────────────────────────────────
    7: [
        q("¿Cuál es la primera etapa del proceso de escritura según el Módulo 7?",
          "La planificación, donde se considera la finalidad, el destinatario, el género y el registro",
          "La puesta en texto, donde se redactan y organizan los párrafos",
          "La revisión, donde se corrigen errores y se ajusta la información",
          "La distribución, donde se decide el formato gráfico del texto",
          "La planificación es el primer momento del proceso escritor; implica definir la finalidad, el destinatario y organizar las ideas antes de escribir.",
          "easy"),
        q("¿Qué tarea corresponde a la etapa de 'puesta en texto'?",
          "Redactar las ideas, construir párrafos coherentes y usar conectores adecuados",
          "Definir el propósito del texto y el género discursivo adecuado",
          "Reflexionar sobre lo escrito y hacer correcciones de puntuación y sintaxis",
          "Recopilar la bibliografía y organizar las fuentes",
          "En la puesta en texto se desarrollan las ideas por escrito, manteniendo coherencia, cohesión y el registro apropiado.",
          "easy"),
        q("¿Por qué la escritura facilita el aprendizaje y la apropiación del conocimiento según Vygotsky?",
          "Porque el lenguaje y el pensamiento están interrelacionados, y el aula es el espacio donde esa interacción se desarrolla",
          "Porque escribir permite copiar las ideas de las fuentes de forma más ordenada",
          "Porque la escritura reemplaza la necesidad de comprender los textos leídos",
          "Porque escribir de manera mecánica garantiza la memorización del contenido",
          "Según Vygotsky (1934), lenguaje y pensamiento se interrelacionan; el aula es el espacio clave para desarrollar esa interacción mediante la escritura.",
          "medium"),
        q("¿En qué consiste la etapa de revisión en el proceso de escritura?",
          "En reflexionar sobre el texto para ajustar información, cambiar el orden, corregir puntuación, sintaxis y errores",
          "En leer los paratextos del texto que se va a escribir para planificar el contenido",
          "En redactar el texto definitivo sin modificaciones posteriores",
          "En compartir el texto con compañeros para que lo corrijan completamente",
          "La revisión es una etapa introspectiva donde el escritor ajusta el texto en todos sus niveles: contenido, estructura, puntuación y ortografía.",
          "medium"),
        q("¿Por qué el módulo afirma que 'no todos saben escribir al llegar a la universidad'?",
          "Porque la escritura académica requiere habilidades específicas que no se desarrollan espontáneamente, sino mediante práctica constante y conciencia de las operaciones involucradas",
          "Porque en la universidad solo se escribe en formatos que los estudiantes nunca han visto antes",
          "Porque la escritura es una habilidad innata que algunos poseen y otros no",
          "Porque el nivel de escritura se deteriora durante la escuela secundaria",
          "La escritura académica es un proceso complejo con dimensiones cognitivas, históricas y sociales que requiere práctica sistemática y conciencia de sus operaciones.",
          "hard"),
    ],

    # ── Módulo 8: Enunciación y Polifonía ─────────────────────────────────────
    8: [
        q("¿Qué son los deícticos en un texto?",
          "Palabras que señalan a las personas, el tiempo y el espacio del acto de enunciación (yo, tú, hoy, aquí)",
          "Términos técnicos que indican la disciplina a la que pertenece el texto",
          "Marcadores textuales que conectan oraciones e indican relaciones lógicas",
          "Paratextos que permiten identificar el género del texto",
          "Los deícticos son palabras que señalan quiénes participan en el discurso y cuándo y dónde ocurre la enunciación.",
          "easy"),
        q("¿Cuál es la diferencia entre el discurso directo y el discurso indirecto?",
          "El directo cita textualmente la voz ajena; el indirecto la introduce mediante paráfrasis o reformulación",
          "El directo usa comillas; el indirecto, cursivas",
          "El directo es oral; el indirecto, escrito",
          "El directo introduce voces colectivas; el indirecto, solo voces individuales",
          "El discurso directo reproduce la cita textual separando claramente las voces; el indirecto reformula la voz ajena subordinándola al enunciador.",
          "easy"),
        q("¿Qué son los subjetivemas?",
          "Palabras que transmiten una valoración del enunciador sobre un objeto, persona o acción (sustantivos, adjetivos, verbos o adverbios con carga evaluativa)",
          "Conectores que expresan la actitud del enunciador mediante el tiempo verbal condicional",
          "Marcas textuales que indican la fuente de una cita bibliográfica",
          "Enunciados impersonales que reflejan leyes científicas universales",
          "Los subjetivemas son palabras con carga valorativa del enunciador: por ejemplo 'casucha' (sustantivo), 'incapaz' (adjetivo) o 'sermoneó' (verbo).",
          "medium"),
        q("¿Para qué se usan las comillas según el Módulo 8?",
          "Para marcar la presencia de otras voces en el discurso, tomar distancia crítica, introducir términos en otra lengua o títulos de textos",
          "Solo para indicar que una palabra es técnica o pertenece a un registro especializado",
          "Para señalar que una oración es una hipótesis que aún no fue demostrada",
          "Para indicar que el enunciador está de acuerdo con lo que cita",
          "Las comillas tienen múltiples funciones: introducir voces ajenas, marcar distancia, señalar términos en otro idioma o irónicos, e introducir títulos o citas directas.",
          "medium"),
        q("¿Por qué los textos académicos y científicos tienden a evitar las marcas de enunciación como los deícticos?",
          "Para mantener una apariencia de objetividad y universalidad, presentando el conocimiento sin marcas de subjetividad",
          "Porque las normas APA prohíben el uso de pronombres personales en todos los casos",
          "Porque los deícticos solo existen en el lenguaje oral y no pueden usarse en la escritura",
          "Para que el texto sea más breve y se adapte a los límites de extensión establecidos",
          "Los textos académicos evitan marcas de enunciación para proyectar objetividad; el conocimiento se presenta como universal, no atribuible a un sujeto particular.",
          "hard"),
    ],

    # ── Generales ─────────────────────────────────────────────────────────────
    0: [
        q("¿Cuál es la diferencia fundamental entre cohesión y coherencia?",
          "La coherencia es una propiedad semántica (unidad temática); la cohesión es una propiedad gramatical (relaciones entre oraciones)",
          "La coherencia usa conectores; la cohesión, pronombres de referencia",
          "La cohesión es global; la coherencia, local",
          "No hay diferencia: son dos nombres para la misma propiedad textual",
          "La coherencia garantiza la unidad temática del texto; la cohesión, los vínculos gramaticales entre sus partes.",
          "medium"),
        q("¿Qué tienen en común la secuencia explicativa y la argumentativa?",
          "Ambas exponen razonadamente un tema respondiendo a un interrogante o fundamentando una posición",
          "Ambas presentan hechos narrados en orden cronológico",
          "Ambas se estructuran siempre con pregunta-respuesta en formato dialogal",
          "Ambas excluyen el uso de ejemplos concretos para mantenerse abstractas",
          "Explicación y argumentación forman un continuum porque las dos exponen razones; la diferencia está en el grado de posicionamiento del enunciador.",
          "medium"),
        q("¿Qué función cumple el contexto histórico, social y cultural en la interpretación de un texto?",
          "Enmarca y posibilita la existencia del texto, aportando circunstancias de época, rasgos sociales e ideas culturales necesarias para interpretarlo íntegramente",
          "Reemplaza al paratexto cuando el texto no tiene título ni datos del autor",
          "Solo es relevante en textos literarios, no en textos académicos o científicos",
          "Determina automáticamente la intención del autor sin necesidad de leer el texto",
          "El contexto histórico-social-cultural complementa el contexto de situación y es indispensable para una lectura crítica y contextualizada.",
          "medium"),
        q("Un estudiante escribe en su parcial una lista de hechos pero no explica las relaciones causales entre ellos. ¿Qué operación cognitiva le falta desarrollar?",
          "Establecer relaciones de causalidad y consecuencia",
          "Generalizar y categorizar la información",
          "Resumir y seleccionar los tramos más relevantes",
          "Usar adecuadamente los conectores temporales",
          "El parcial requiere no solo informar sino también explicar y justificar; establecer relaciones causales es una de sus operaciones esenciales.",
          "hard"),
        q("¿Cuál es la función de las normas APA en la escritura académica?",
          "Estandarizar las referencias bibliográficas para evitar el plagio y permitir identificar las fuentes citadas",
          "Regular el formato visual (tipografía, márgenes) de los trabajos universitarios",
          "Establecer el vocabulario permitido en los textos científicos",
          "Indicar qué autores tienen autoridad suficiente para ser citados en un trabajo académico",
          "Las normas APA permiten citar correctamente las fuentes, lo cual es fundamental para evitar el plagio y facilitar una lectura crítica contextualizada.",
          "easy"),
        q("¿Por qué un parcial escrito es considerado un 'diálogo asimétrico'?",
          "Porque el docente pregunta desde una posición de autoridad y el estudiante debe responder demostrando dominio de los contenidos evaluados",
          "Porque el estudiante puede elegir libremente qué preguntas responder según su comodidad",
          "Porque ambos interlocutores tienen el mismo nivel de conocimiento sobre el tema",
          "Porque el diálogo se realiza en forma oral y no deja registro escrito",
          "El parcial es asimétrico porque hay una relación de poder: el docente pregunta y evalúa; el estudiante debe responder ajustándose a consignas específicas.",
          "medium"),
        q("¿Qué diferencia al resumen de una simple reducción del texto original?",
          "El resumen tiene una finalidad argumentativa específica y aplica operaciones como selección, omisión, generalización e integración",
          "El resumen solo acorta el texto copiando las oraciones más importantes",
          "El resumen elimina todos los ejemplos para quedarse solo con las definiciones",
          "El resumen siempre se escribe en primera persona para marcar la voz del estudiante",
          "El resumen no es un recorte: aplica macrorreglas (selección, omisión, generalización, integración) con una finalidad argumentativa y es un texto autónomo.",
          "hard"),
        q("¿Qué caracteriza a la polifonía enunciativa en un texto?",
          "La inclusión de voces distintas a la del enunciador, que pueden atribuirse a otros enunciadores concretos o ser voces colectivas sin asignación específica",
          "La presencia de un único enunciador que desarrolla su argumento sin referencias externas",
          "El uso de un registro formal que elimina toda subjetividad del texto",
          "La repetición de las mismas ideas con distintas palabras para reforzar la cohesión",
          "La polifonía refiere a las voces ajenas que el enunciador incorpora en su discurso, ya sea atribuyéndolas a alguien concreto o dejándolas sin asignación.",
          "medium"),
        q("Un texto comienza con 'Sabemos que...' y presenta una creencia generalizada para luego refutarla. ¿Qué estrategia argumentativa está usando?",
          "Desmentida: negación de una supuesta verdad previamente establecida",
          "Concesión: aceptación parcial del pensamiento del otro",
          "Anécdota: narración de un hecho personal para probar la hipótesis",
          "Argumento de sentido común: uso de creencias difundidas como verdades",
          "La desmentida niega una supuesta verdad; es habitual comenzar con 'Podría argumentarse que...' o 'Sabemos que...' para luego refutarla.",
          "hard"),
        q("¿Cuál es la función del apunte de clase como género académico?",
          "Fijar por escrito el contenido de la clase para conservarlo con fines de estudio personal",
          "Comunicar conocimiento elaborado a otros estudiantes o al docente",
          "Reemplazar la lectura de la bibliografía obligatoria del curso",
          "Presentar argumentos originales del estudiante sobre los temas tratados",
          "El apunte es un género simple destinado al propio estudiante para conservar el contenido de la clase; no está pensado para comunicar conocimiento a otros.",
          "easy"),
    ],
}
